### ISSUE TITLE
Using 'bootstrap' vs 'autoreconf'

### ISSUE THREAD

**Issue by sirjaren** [utsushi/utsushi#13]
Hello,

This is more a request for information, rather than an issue.

I've played with the `utsushi` source code a bit (mainly compiling it for `gentoo`).  I've been able to successfully compile using `autools` provided by gentoo (`autoreconf`, which includes using `libtool`, `aclocal`, etc), without using the `bootstrap` wrapper.

I'm curious if that's acceptable, or is using the `bootstrap` wrapper required?  I did notice some patches are being done with `bootstrap`.  I did find a bug with the  `ltmain.sh` patch, which I'll submit a pull request for later.

Thanks for any information!

PS. I did notice that in the newer sources, someone added the `sed` to strip the `git` tag from `pkg-config`'s output.  Thank you!  That makes supporting `utsushi`/`imagescan` that much easier. :smile:

**Comment by paddy-hack** [comment]
Acceptable?  As long as you apply the patch to `ltmain.sh`, I guess so.

Why do you prefer to run `autoreconf` directly?  The only thing I can think of is that you don't want a build dependency on `gnulib-tool`.

As for the `pkg-config` patch, yes, thanks!  The Ubuntu build for `wily` :bomb:'ed on that.

**Comment by sirjaren** [comment]
Thanks for the response!

The reason I asked is because I already had the `autools` suite installed, and was curious about the additional dependencies I needed:
- `gnulib-tool`
- `autoconf-archive`

Additionally, I was asking since I'm creating a `Gentoo` installation `ebuild` for `utsushi`, and found it's easier to use `Gentoo`'s wrappers around `autoreconf`, called `eautoreconf`, and drop the two dependencies above.

Anyways, it's not hard to support the `bootstrap` method, and frankly, if you're using that and supporting it, then by all means, I'll continue to use it.  I just wanted to note using `autoreconf`.

Thanks _paddy-hack_!  This can be closed now.

**Comment by paddy-hack** [comment]
Then why don't you do so :wink:
