### ISSUE TITLE
building fails with undefined reference to utsushi::pump::connect

### ISSUE THREAD

**Issue by pniederlag** [utsushi/utsushi#18]
Does anyne have an advice on my problem during "sudo make install"?

``` c
make[3]: Verzeichnis „/fileserver/usr-local-src/utsushi/src“ wird betreten
  CXX      main.o
  CXXLD    main
  CXX      version.o
  CXXLD    version
  CXX      help.o
  CXXLD    help
  CXX      list.o
  CXXLD    list
  CXX      scan.o
  CXXLD    scan
  CXX      scan-cli.o
  CXXLD    scan-cli
  CXX      scan_gtkmm-scan-gtkmm.o
  CXXLD    scan-gtkmm
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::pump::connect(boost::signals2::slot<void (utsushi::log::priority, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >), boost::function<void (utsushi::log::priority, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)> > const&) const'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::pump::pump(std::shared_ptr<utsushi::idevice>)'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::pump::start(std::shared_ptr<utsushi::odevice>)'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::pump::start(std::shared_ptr<utsushi::stream>)'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::option::map::builder::operator()(utsushi::key const&, std::shared_ptr<utsushi::option::map>) const'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::stream::push(std::shared_ptr<utsushi::odevice>)'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::stream::push(std::shared_ptr<utsushi::filter>)'
../gtkmm/.libs/libutsushi-gtkmm.so: undefined reference to `utsushi::scanner::create(std::shared_ptr<utsushi::connexion>, utsushi::scanner::info const&)'
collect2: error: ld returned 1 exit status
Makefile:622: die Regel für Ziel „scan-gtkmm“ scheiterte
make[3]: *** [scan-gtkmm] Fehler 1
```

**Comment by paddy-hack** [comment]
It might be helpful if you can tell how you ran `configure` and what that produced.  I am assuming you ran `sudo make install` from the top-level source directory.  From #17, I also assume you are trying to build on Debian's `stretch`.  If your installation is reasonably up-to-date, you probably should

```
./configure CXXFLAGS="-std=c++11"
```

as some of the files included by the `gtkmm/` code require that.  When you build part of the code at C++11, you need to build _all_ of the code at C++11.  You may need to run a `make clean` to make sure everything is recompiled.  There is some more info on the C++11 issue in #16.

The errors you show above hint at the code in `lib/` (at the very least) having been compiled to use the Boost versions of `shared_ptr` whereas the `gtkmm/` want `std::shared_ptr`.

**Comment by pniederlag** [comment]
```
./configure CXXFLAGS="-std=c++11"
```

fixes the issue and have the first working binary.

Many thx for your support and sry for not giving you more details on the problem in first place. As you can probabley guess I am not familiar with c, c++ and building software. I am just looking for a solution to get the scanner working efficiently on my debian testing/sid box.

**Comment by paddy-hack** [comment]
Glad that fixed things for you.
