### ISSUE TITLE
DS-40 not detected on ubuntu 16.04

### ISSUE THREAD

**Issue by Qwertie-** [utsushi/utsushi#20]
I compiled the driver with `./configure CXXFLAGS="-std=c++11"` and `make` and started it with `srcdir=. ./scan-gtkmm` but its not showing any device to scan with.

`srcdir=. ./main list` shows `usb::/sys/devices/pci0000:00/0000:00:14.0/usb3/3-10/3-10:1.0` and syslog shows

`lsusb` shows `Bus 003 Device 009: ID 04b8:0152 Seiko Epson Corp.`

I did have it working when I compiled it on ubuntu 15.10 though

**Comment by paddy-hack** [comment]
Did you `sudo make install`?  Probably not.
At the very least you need to

```
sudo install ./drivers/esci/utsushi-esci.rules /etc/udev/rules.d/
```

and replug your scanner.  That should make it work without installing _all_ of Utsushi.
After the `udev` rules file is in place, a `scrdir=. ./main list` should show `usb:utsushi:/sys/devices/...`.  Note the `utsushi` between the colons.

**Comment by Qwertie-** [comment]
Installing it did solve the problem but I don't really like installing things outside of the package manager. Are there any instructions on how I could package utsushi into a .deb?

**Comment by paddy-hack** [comment]
You don't have to install the whole lot.  Just the `udev` rules needs to be put in place.  The only places `udev` looks are system locations (see the `udev` manual page's `RULES FILES` section for details).  The `install` _command_, as opposed to a `make install`, is basically just a thin wrapper around `cp`.  Have a look at the manual page.
The files below `/etc/udev/rules.d/` _are_ for the system administrator to maintain.  The `.deb`s should be putting theirs in `/lib/udev/` (or maybe `/lib/systemd/udev/`).

> Are there any instructions on how I could package utsushi into a .deb?

You could take a look at the files available at the EPSON Dowload Center.  This is where I get the original source tarballs for the [utsushi/imagescan](https://github.com/utsushi/imagescan) project that get merged here.  There are a number of `.debian.tar.xz` files as well and I would assume the one for `ubuntu15.10` is a good starting point.  Actually, you may not even have to change anything if all you want is a `.deb`.  The URL can be found in the commit message of cffbd6a, for example.
