### ISSUE TITLE
XP-635 scanner installation

### ISSUE THREAD

**Issue by danield5732** [utsushi/utsushi#21]
Hello,

I  try to get the epson scanner XP-635 working, but unfortunately without success on Ubuntu 14.04 and 16.04 and on two notebooks. My aim is to scan with simple-scan, but the behavior is quite strange.

On 14.04 the scanner isn't detected by 'sudo sane-find-scanner' (so also not by simple-scan), but imagescan (installed via .deb from epson) seams to work and comes up with a pretty preview image. The scan itself is also processing, but no image is saved anyway, also no error occurs.

On 16.04 I tried to install utsushi from source, but it doesn't finished completely. However the scanner is detected by simple-scan afterwards. It also processes a scan but no image is shown up on screen.

I hope you can help me in this case. If you need any more information just ask for it, please.

Best regards,
Daniel

**Comment by paddy-hack** [comment]
On 14.04, `imagescan list` should produce something that looks like `usb:esci:/sys/devices/usb/...`.  I may have gotten the `usb` and `esci` bits the wrong way around though (writing from memory :wink:).  That fact the `sane-find-scanner` doesn't find it, does _not_ mean `simple-scan` cannot find it.  In fact, I would expect it to find the scanner.

I assume that the pretty preview only displays _after_ you preview, not by simply starting the application.  The fact that you see no errors, unfortunately, does not mean there weren't any.  `imagescan` (and `utsushi`) don't log anything by default (see #10).

On 16.04, when you say that the install doesn't finish completely, what parts _exactly_ don't finish.  A log would be most helpful.  Try

```
sudo make install 2>&1 | tee install.log
```

and attach the `install.log` here.
After that, modify `lib/log.cpp` as described in #6 and

```
make
sudo make install 2>&1 | tee install2.log
simple-scan 2> simple-scan.log
```

and attach both log files.

**Comment by danield5732** [comment]
Thanks for your quick response!

I attach install.log and install2.log (after modification of `lib/log.cpp` as described in #10 ) from ubuntu 16.04.

The simple-scan.log I'll attach tomorrow, because the device isn't right here, sorry for that.

[install.txt](https://github.com/utsushi/utsushi/files/289731/install.txt)
[install2.txt](https://github.com/utsushi/utsushi/files/289730/install2.txt)

**Comment by paddy-hack** [comment]
OK, I see.  You've got the same undefined symbols as in #18.  See there for info on how to fix this.

**Comment by danield5732** [comment]
You are right, the installation passed successfully now!

Unfortunately the scan doesn't finish with an image. The behavior of utsushi on Ubuntu 16.04 is now the same like it is on Ubuntu 14.04 with imagescan.

Here are the logs from the scan:
[simple-scan.txt](https://github.com/utsushi/utsushi/files/291816/simple-scan.txt)
[utsushi.txt](https://github.com/utsushi/utsushi/files/291817/utsushi.txt)

By the way, the output from `imagescan list` on Ubuntu 14.04 shows:
`usb:esci:/sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.1/2-1.1:1.0`

**Comment by paddy-hack** [comment]
I think there's a bug in the setting of the colour matrix values.  It's passing values with a `,` as the decimal "point" instead of the `.` expected.  If so, it's a `locale` issue.  What is the output when you execute that command?

**Comment by paddy-hack** [comment]
I just reproduced your problem by calling `convert` from the command-line.  This is just what `utsushi` does under the covers anyway, so that simplifies things.  Replacing all the `,` with `.` fixed the `convert` invocation.  I think that

```
LC_NUMERIC=C utsushi
```

will work around your problem for now.

**Comment by danield5732** [comment]
Hello again and thank you very much for your patience!
With the work around the scan performs very well!

There is just an other point I'm struggling with. The second Laptop (I upgraded to Ubuntu 16.04 now) works fine with utsushi and the work around as well, but simple-scan and xsane just doesn't recognize the scanner. I'm wondering about that, because `sudo sane-find-scanner` finds it after the installation of utsushi.

If you can give a hint would be great, but actually I'm very happy about your help until now.

Kind regards,
Daniel

**Comment by paddy-hack** [comment]
I think something went wrong hooking `utsushi` in the SANE setup.  See if this fixes things

```
cd sane
sudo make install-data
```

If not, please attach the output of the above command.

If all went well you should have an `/etc/sane/dll.d/utsushi` file and I would expect SANE frontends such as simple-scan and xsane to be able to use your scanner.

BTW, `sane-find-scanner` only checks for _physical presence_.  It says absolutely _nothing_ about whether SANE frontends can use it.

**Comment by danield5732** [comment]
This is the output, but '/etc/sane/dll.d/utsushi' still exists.

```
ruediger@ruediger-Aspire-E1-571:~/Downloads/utsushi-master/sane$ sudo make install-data
[sudo] Passwort für ruediger: 
Making install-data in .
make[1]: Verzeichnis „/home/ruediger/Downloads/utsushi-master/sane“ wird betreten
make  install-data-hook
make[2]: Verzeichnis „/home/ruediger/Downloads/utsushi-master/sane“ wird betreten
if test -d "/etc/sane.d/dll.d"; then \
  dirname="/etc/sane.d/dll.d"; \
  file=$dirname/utsushi; \
  test -d $dirname || /bin/mkdir -p $dirname; \
  echo "#  utsushi -- dll.conf snippet" > $file; \
  echo "" >> $file; \
  echo "utsushi" >> $file; \
else \
  dirname="/etc/sane.d"; \
  file=$dirname/dll.conf; \
  if test -f $file; then \
    if test -n "`/bin/grep '^[ \t]*#[ \t#]*utsushi' $file`"; \
    then \
      sed -i 's,^[ \t]*#[ \t#]*\(utsushi\),\1,' $file; \
    elif test -z "`/bin/grep utsushi $file`"; then\
      echo utsushi >> $file; \
    fi; \
  else \
    echo -n "WARNING: $file not found,"; \
    echo " cannot activate SANE component"; \
  fi; \
fi
make[2]: Verzeichnis „/home/ruediger/Downloads/utsushi-master/sane“ wird verlassen
make[1]: Verzeichnis „/home/ruediger/Downloads/utsushi-master/sane“ wird verlassen
Making install-data in tests
make[1]: Verzeichnis „/home/ruediger/Downloads/utsushi-master/sane/tests“ wird betreten
make[1]: Für das Ziel „install-data“ ist nichts zu tun.
make[1]: Verzeichnis „/home/ruediger/Downloads/utsushi-master/sane/tests“ wird verlassen
ruediger@ruediger-Aspire-E1-571:~/Downloads/utsushi-master/sane$
```

Maybe it is necessary to reinstall sane it self in total? I don't get it..

**Comment by paddy-hack** [comment]
Neither do I, but if you can provide the debug output of

```
SANE_DEBUG_DLL=127 xsane
```

I might just be able to figure it out.  More so if you run this with the Utsushi version where you enabled its logging.

**Comment by danield5732** [comment]
Very interesting, the notebook with the problem doesn't output anything! Immediately a small window pops up with the message that no scanner is reachable.

Doing `SANE_DEBUG_DLL=127 xsane` with the other notebook, that detects the scanner. It produces a large output and first shows a small windows with "searching for scanner" and if no scanner is pluged in, the message "no scanner is reachable." appears.
(messages are transalted freely)

Thank you for your efforts!

**Comment by paddy-hack** [comment]
That's weird.  On the notebook with the problem, does `lsusb -d 04b8:` list the scanner?  Does it work with Utsushi?  If the answer to both questions is yes, you have a problem with your SANE installation.  I'd suggest asking around on the Ubuntu forums.

Oh, it might be a permission problem.  If you run `sudo simple-scan` or `sudo xsane`, does that find the scanner?  Note, `xsane` will warn about running as `root`.  If that works, you may need to add yourself to the `plugdev` or `scanner` group, log out and back in again.  Hope this helps.
