### ISSUE TITLE
DS-520 - not supported error!?

### ISSUE THREAD

**Issue by d0b3rm4n** [utsushi/utsushi#26]
I have some troubles to get the DS-520 working, which should be supported by this software. Reading the other issues here, it seems often the problem is a missing udev rules file, but that seems to be in place:

    # ls -al /etc/udev/rules.d/utsushi-esci.rules 
    -rw-r--r--. 1 root root 5024 Jan  5 20:26 /etc/udev/rules.d/utsushi-esci.rules

Also it seems the rules are applied:

    # udevadm info /dev/bus/usb/001/014
    P: /devices/pci0000:00/0000:00:14.0/usb1/1-4
    N: bus/usb/001/014
    E: BUSNUM=001
    E: DEVNAME=/dev/bus/usb/001/014
    E: DEVNUM=014
    E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-4
    E: DEVTYPE=usb_device
    E: DRIVER=usb
    E: ID_BUS=usb
    E: ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_4
    E: ID_MODEL=Epson_DS-520
    E: ID_MODEL_ENC=Epson\x20DS-520
    E: ID_MODEL_ID=0154
    E: ID_PATH=pci-0000:00:14.0-usb-0:4
    E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_4
    E: ID_REVISION=0001
    E: ID_SERIAL=EPSON_Epson_DS-520
    E: ID_USB_INTERFACES=:ffffff:
    E: ID_VENDOR=EPSON
    E: ID_VENDOR_ENC=EPSON
    E: ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
    E: ID_VENDOR_ID=04b8
    E: MAJOR=189
    E: MINOR=13
    E: PRODUCT=4b8/154/1
    E: SUBSYSTEM=usb
    E: TAGS=:uaccess:seat:
    E: TYPE=255/255/255
    E: USEC_INITIALIZED=4864158988
    E: libsane_matched=yes
    E: utsushi_driver=esci

    # udevadm info --path=/devices/pci0000:00/0000:00:14.0/usb1/1-4
    P: /devices/pci0000:00/0000:00:14.0/usb1/1-4
    N: bus/usb/001/014
    E: BUSNUM=001
    E: DEVNAME=/dev/bus/usb/001/014
    E: DEVNUM=014
    E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-4
    E: DEVTYPE=usb_device
    E: DRIVER=usb
    E: ID_BUS=usb
    E: ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_4
    E: ID_MODEL=Epson_DS-520
    E: ID_MODEL_ENC=Epson\x20DS-520
    E: ID_MODEL_ID=0154
    E: ID_PATH=pci-0000:00:14.0-usb-0:4
    E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_4
    E: ID_REVISION=0001
    E: ID_SERIAL=EPSON_Epson_DS-520
    E: ID_USB_INTERFACES=:ffffff:
    E: ID_VENDOR=EPSON
    E: ID_VENDOR_ENC=EPSON
    E: ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
    E: ID_VENDOR_ID=04b8
    E: MAJOR=189
    E: MINOR=13
    E: PRODUCT=4b8/154/1
    E: SUBSYSTEM=usb
    E: TAGS=:seat:uaccess:
    E: TYPE=255/255/255
    E: USEC_INITIALIZED=4864158988
    E: libsane_matched=yes
    E: utsushi_driver=esci

but `utsushi` command as user and `root` does not list anything.

    $ utsushi list
    $ utsushi scan --no-interface
     no usable devices available

While `strace`-ing `utsushi` I noticed that it tries to read a utsushi.conf, so I thought I help it a little.
So I created a `/usr/local/etc/utsushi/utsushi.conf` with a line `dev1.udi=usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4`. Now I get a `not supported`

    # cat /usr/local/etc/utsushi/utsushi.conf
    [devices]
    dev1.udi=usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4

    $ utsushi list
    usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4
    $ utsushi scan --no-interface
    usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4: not supported

last few lines of `strace` output:

    $ strace utsushi scan --no-interface
    open("/usr/local/share/locale/en_GB.UTF-8/LC_MESSAGES/utsushi.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/local/share/locale/en_GB.utf8/LC_MESSAGES/utsushi.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/local/share/locale/en_GB/LC_MESSAGES/utsushi.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/local/share/locale/en.UTF-8/LC_MESSAGES/utsushi.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/local/share/locale/en.utf8/LC_MESSAGES/utsushi.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
    open("/usr/local/share/locale/en/LC_MESSAGES/utsushi.mo", O_RDONLY) = 3
    fstat(3, {st_mode=S_IFREG|0644, st_size=557, ...}) = 0
    mmap(NULL, 557, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fbf405b1000
    close(3)                                = 0
    stat("/usr/local/etc/utsushi/utsushi.conf", {st_mode=S_IFREG|0644, st_size=70, ...}) = 0
    open("/usr/local/etc/utsushi/utsushi.conf", O_RDONLY) = 3
    read(3, "[devices]\ndev1.udi=usb:esci:/dev"..., 8191) = 70
    read(3, "", 8191)                       = 0
    close(3)                                = 0
    open("/usr/local/lib/utsushi/libdrv-esci.la", O_RDONLY) = 3
    fstat(3, {st_mode=S_IFREG|0755, st_size=1061, ...}) = 0
    read(3, "# libdrv-esci.la - a libtool lib"..., 4096) = 1061
    read(3, "", 4096)                       = 0
    close(3)                                = 0
    futex(0x7fbf3d9560a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    open("/usr/local/lib/utsushi/libdrv-esci.so.0", O_RDONLY|O_CLOEXEC) = 3
    read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\10\r\0\0\0\0\0"..., 832) = 832
    fstat(3, {st_mode=S_IFREG|0755, st_size=153752728, ...}) = 0
    mmap(NULL, 4537712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fbf35aac000
    mprotect(0x7fbf35cf5000, 2093056, PROT_NONE) = 0
    mmap(0x7fbf35ef4000, 49152, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x248000) = 0x7fbf35ef4000
    close(3)                                = 0
    mprotect(0x7fbf35ef4000, 36864, PROT_READ) = 0
    futex(0x7fbf3e3531a0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
    write(2, "usb:esci:/devices/pci0000:00/000"..., 65usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4: not supported) = 65
    write(2, "\n", 1
    )                       = 1
    exit_group(1)                           = ?
    +++ exited with 1 +++

`scanimage` complains about `Operation not supported` (in `/etc/sane.d/dll.conf` I needed to comment out `epsonds`, otherwise it tries to use the epsonds backend)

    $ scanimage -L
    device `utsushi:usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4' is a
    $ scanimage -T
    scanimage: open of device utsushi:usb:esci:/devices/pci0000:00/0000:00:14.0/usb1/1-4 failed: Operation not supported

The sane config and sane backend libraries, seem to be in the correct location:

    # ls -al /etc/sane.d/dll.d/utsushi 
    -rw-r--r--. 1 root root 40 Jan  5 18:38 /etc/sane.d/dll.d/utsushi
    # ls -al /usr/lib64/sane/libsane-utsushi.*
    lrwxrwxrwx. 1 root root 47 Jan  5 18:38 /usr/lib64/sane/libsane-utsushi.la -> ../../local/lib/utsushi/sane/libsane-utsushi.la
    lrwxrwxrwx. 1 root root 47 Jan  5 18:38 /usr/lib64/sane/libsane-utsushi.so -> ../../local/lib/utsushi/sane/libsane-utsushi.so
    lrwxrwxrwx. 1 root root 49 Jan  5 18:38 /usr/lib64/sane/libsane-utsushi.so.1 -> ../../local/lib/utsushi/sane/libsane-utsushi.so.1
    lrwxrwxrwx. 1 root root 54 Jan  5 18:38 /usr/lib64/sane/libsane-utsushi.so.1.0.25 -> ../../local/lib/utsushi/sane/libsane-utsushi.so.1.0.25
     # ls -la /usr/local/lib/utsushi/sane/
    total 7116
    drwxr-xr-x. 1 root root     186 Jan  5 18:38 .
    drwxr-xr-x. 1 root root     648 Jan  5 18:38 ..
    lrwxrwxrwx. 1 root root      25 Jan  5 18:38 libsane.so.1 -> libsane-utsushi.so.1.0.25
    -rwxr-xr-x. 1 root root    1191 Jan  5 18:38 libsane-utsushi.la
    lrwxrwxrwx. 1 root root      25 Jan  5 18:38 libsane-utsushi.so -> libsane-utsushi.so.1.0.25
    lrwxrwxrwx. 1 root root      25 Jan  5 18:38 libsane-utsushi.so.1 -> libsane-utsushi.so.1.0.25
    -rwxr-xr-x. 1 root root 7267568 Jan  5 18:38 libsane-utsushi.so.1.0.25
    #

Any idea what could be missing, or how to debug further?

**Comment by d0b3rm4n** [comment]
ok found the problem, `libudev` header files resp. `systemd-devel` (where now a days udev support is coming from) package was missing. Would be nice if `./configure` fails spectacularly and not silently pretends all is fine, since libudev support seems to be needed!

```
$ utsushi list
2017-Jan-05 22:19:40.837414[140558465644608]: /usr/local/etc/utsushi/utsushi.conf: no such file
2017-Jan-05 22:19:40.837514[140558465644608]: no such file: /usr/local/etc/utsushi/utsushi.conf
usb:esci:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0
```

also `utsushi scan` scans in papers now.

**Comment by paddy-hack** [comment]
Please submit an issue requesting the `./configure` "failure" in case the `libudev` headers cannot be found.

I should point out that network scanners ought to work fine without them, though.
