### ISSUE TITLE
[L375] networkscan - Can't connect to scanner

### ISSUE THREAD

**Issue by leosanvieira** [utsushi/utsushi#28]
Forgive me if you don't see this as fit, as is related to Epson proprietary plugin.

I compiled an utsushi package for Arch Linux, it's working through USB using the utsushi app, but when i try connecting through networkscan plugin, i get the following messages:

Any insights?

/usr/local/etc/utsushi/utsushi.conf
net.udi       = esci:networkscan://{scanner_ip}:1865
net.vendor = Epson
net.model  = L375

utsushi
2017-Mar-27 10:35:41.550382[139872455297344]: some device not found. delete combo::?adf=esci:usb:04b8:0155&fb=esci:gt-s650:usb:04b8:013c
2017-Mar-27 10:35:41.551070[139872455297344]: some device not found. delete combo::?adf=esci:usb:04b8:0156&fb=esci:gt-s650:usb:04b8:013c
2017-Mar-27 10:35:41.551605[139872455297344]: some device not found. delete combo::?adf=esci:usb:04b8:0157&fb=esci:gt-s650:usb:04b8:013c
2017-Mar-27 10:35:41.552132[139872455297344]: some device not found. delete combo::?adf=esci:usb:04b8:0155&fb=esci:gt-s650:usb:04b8:013d
2017-Mar-27 10:35:41.552658[139872455297344]: some device not found. delete combo::?adf=esci:usb:04b8:0156&fb=esci:gt-s650:usb:04b8:013d
2017-Mar-27 10:35:41.553191[139872455297344]: some device not found. delete combo::?adf=esci:usb:04b8:0157&fb=esci:gt-s650:usb:04b8:013d
2017-Mar-27 10:35:41.607600[139872455297344]: looking for preloaded 'esci' driver
2017-Mar-27 10:35:41.607740[139872455297344]: looking for 'esci' driver in '/usr/local/lib/utsushi'
2017-Mar-27 10:35:41.617408[139872455297344]: using '/usr/local/lib/utsushi/libdrv-esci'
2017-Mar-27 10:35:41.618750[139872455297344]: /usr/local/libexec/utsushi/networkscan[3096]: starting
2017-Mar-27 10:35:44.636280[139872455297344]: connect: Operation now in progress
2017-Mar-27 10:35:48.689568[139872455297344]: connect: Operation now in progress
2017-Mar-27 10:35:52.742905[139872455297344]: connect: Operation now in progress
2017-Mar-27 10:35:56.796396[139872455297344]: connect: Operation now in progress
2017-Mar-27 10:36:00.849603[139872455297344]: connect: Operation now in progress
2017-Mar-27 10:36:00.850279[139872204916480]: terminating /usr/local/libexec/utsushi/networkscan (port 38185)
2017-Mar-27 10:36:00.851394[139872204916480]: /usr/local/libexec/utsushi/networkscan[3096]: exited with status 0

**Comment by paddy-hack** [comment]
The `combo::` messages are not relevant, I think.  They look like they are probing for a "device" that is really a combination of an ADF-only and a flatbed-only device.

The `/usr/local/libexec/utsushi/networkscan` process seems to start up fine but seems unable to connect to your networked scanner and seems to give up after five tries.  That's a lot of *seems* but without access to source code, I can only guess.

From the machine where you run `utsushi`, can you connect to port 1865 on the scanner with `telnet`?  If you can, I cannot help you any further.  If you cannot, you probably have a networking issue.  Would you happen to have a firewall somewhere between the computer and the scanner?

**Comment by leosanvieira** [comment]
Thanks paddy-hack, it was truly a firewall problem, it seems networkscan uses a dynamic high port to receive data.

**Comment by paddy-hack** [comment]
> networkscan uses a dynamic high port to receive data

I was under the impression that `networkscan` connects and talks to the scanner's 1865 port and that it runs in a separate process where the communication between `utsushi` and `networkscan` is on a dynamic high port.  The latter communication is all within `localhost` bounds, though.

**Comment by leosanvieira** [comment]
I'm no expert on the subject, but it doesn't seem so. As you can see below from the result of ss -ntpu command after utsushi gui started, networkscan uses a high dynamic port to talk to the scanner's 1865 port.
```
Netid  State Recv-Q Send-Q             Local Address:Port           Peer Address:Port
tcp    ESTAB      0      0             {PC_IP}:49200                {SCANNER_IP}:1865
users:(("networkscan",pid=2604,fd=3))
tcp    ESTAB      0      0             127.0.0.1:36181              127.0.0.1:36196
users:(("networkscan",pid=2604,fd=4))
tcp    ESTAB      0      0             127.0.0.1:36196              127.0.0.1:36181
users:(("utsushi-scan-gt",pid=2599,fd=8))
```

**Comment by paddy-hack** [comment]
The fact the `networkscan` uses a dynamically allocated port to talk to your scanner (at a dedicated port) is nothing special.  Just about any program does that, `ssh`, your web browser, ...

So your firewall needs to allow outgoing traffic to `{SCANNER_IP}:1865` and any incoming replies that generates.

**Comment by leosanvieira** [comment]
Yes, that's basically it, but my firewall was blocking the reply for some reason, but it's solved now.
