### ISSUE TITLE
failing to build

### ISSUE THREAD

**Issue by teamblubee** [utsushi/utsushi#29]
Hello

I am working with the latest version of this project. I am porting it to FreeBSD I am making some changes but now I am having trouble building, it's failing with this error.

I am on FreeBSD 12-Current

```shell
echo $CC : gcc
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc49/gcc/x86_64-portbld-freebsd12.0/4.9.4/lto-wrapper
Target: x86_64-portbld-freebsd12.0
Configured with: /usr/ports/lang/gcc/work/gcc-4.9.4/configure --disable-bootstrap --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc49 --libexecdir=/usr/local/libexec/gcc49 --program-suffix=49 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc49/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --disable-libgcj --enable-languages=c,c++,objc,fortran --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc49 --build=x86_64-portbld-freebsd12.0
Thread model: posix
gcc version 4.9.4 (FreeBSD Ports Collection) 


echo $CXX : gcc++
% g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc49/gcc/x86_64-portbld-freebsd12.0/4.9.4/lto-wrapper
Target: x86_64-portbld-freebsd12.0
Configured with: /usr/ports/lang/gcc/work/gcc-4.9.4/configure --disable-bootstrap --disable-nls --enable-gnu-indirect-function --libdir=/usr/local/lib/gcc49 --libexecdir=/usr/local/libexec/gcc49 --program-suffix=49 --with-as=/usr/local/bin/as --with-gmp=/usr/local --with-gxx-include-dir=/usr/local/lib/gcc49/include/c++/ --with-ld=/usr/local/bin/ld --with-pkgversion='FreeBSD Ports Collection' --with-system-zlib --disable-libgcj --enable-languages=c,c++,objc,fortran --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/info/gcc49 --build=x86_64-portbld-freebsd12.0
Thread model: posix
gcc version 4.9.4 (FreeBSD Ports Collection) 


make
make  all-recursive
Making all in .
Making all in lib
Making all in .
  CXX      connexion.lo
In file included from connexion.cpp:44:
../utsushi/log.hpp:155:36: error: instantiation of variable 'utsushi::log::basic_logger<char, std::__1::char_traits<char> >::os_' required here,
      but no definition is available [-Werror,-Wundefined-var-template]
      basic_logger<charT, traits>::os_ << *this;
                                   ^
../utsushi/log.hpp:265:23: note: in instantiation of member function 'utsushi::log::basic_message<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >::~basic_message' requested here
  expand_named_ctors (fatal, FATAL);
                      ^
../utsushi/log.hpp:49:47: note: forward declaration of template entity is here
    static std::basic_ostream<charT, traits>& os_;
                                              ^
1 error generated.
*** Error code 1

Stop.
make[3]: stopped in /usr/home/usr/Downloads/Epson/ut/lib
*** Error code 1

Stop.
make[2]: stopped in /usr/home/usr/Downloads/Epson/ut/lib
*** Error code 1

Stop.
make[1]: stopped in /usr/home/usr/Downloads/Epson/ut
*** Error code 1

Stop.
make: stopped in /usr/home/usr/Downloads/Epson/ut
```

**Comment by paddy-hack** [comment]
The [Travis build](https://travis-ci.org/utsushi/utsushi/builds/227467976) for 86420d5 passes for gcc 4.8.4 (Ubuntu 14.04), but fails with clang for reasons very different from what you report.  I have no experience trying to build on BSDs.  My own builds at home are on Debian jessie (gcc 4.9.2).  Upstream provides binaries for a number of distributions, not sure what gcc versions are being used.

That said, the error message does seem somewhat familiar.  I've "walked" up the include chain but there is no explicit include for `<ostream>`.  I think `utsushi/log.hpp` has been free-riding on `<boost/format.hpp>` or some other header file including this.  Try adding an
``` c++
#include <ostream>
```
in `utsushi/log.hpp`.  If that doesn't work, try `<iostream>`.

**Comment by teamblubee** [comment]
Hi, 
I was able to get past that issue by setting up some more env variables. 

I am having issues with the make command. There are differences between gnu see and FreeBSD see. 

```shell

$(srcdir)/utsushi/tag.hpp $(srcdir)/lib/tag.cpp: $(srcdir)/lib/tag.xml \
  $(srcdir)/lib/tag.xsl
	format=`echo $@ | sed 's|.*\.\([^.]*\)$$|\1|'`; \
	sed -n \
	    -e "/^<!--/s/\.xml ::/.$$format --/" \
	    -e '/^<!--/,/-->/{ /-->/d; s|^$$|//|p; s|^....|//|p; }' $< > $@; \
	xsltproc --stringparam format $$format $(srcdir)/lib/tag.xsl $< >> $@
	sed -i 's/SEC_N_("%1%")/"%1%"/' $@
```

I can tell that this command is taking the xsl & xml tags file, making a header & cop file and suppose to put them in the proper places. 

that's not working for me. The command just hang there. 

Here is more info. https://forums.freebsd.org/threads/61253/

Would you be able to help me untangle that command, see what it's doing and then I should be able to come to with a patch that gets these new drivers in FreeBSD.

**Comment by paddy-hack** [comment]
Good to see that you got passed the `utsushi::log::basic_logger<char, std::__1::char_traits<char> >::os_` instantiation compile time error.  I'd like to know how you did that.  Your "setting up some more env variables" isn't very descriptive in case someone stumbles on this issue.

I would have preferred you had opened *another* issue for the `sed` issue.  It's better to keep unrelated things, well, unrelated.  I've opened #31 for that and will close this but if you would elaborate on solving the compile error, that'd be appreciated.
