### ISSUE TITLE
The Imagescan icon won't appear on the gnome or unity dashboard once imagescan is launched.

### ISSUE THREAD

**Issue by jugalnet** [utsushi/utsushi#30]
Imagescan icon of the icon pack in use shows up in the launcher but it won't show up on the gnome or unity dahsboard once the application is launched. I have attached the .desktop file and a video showing the issue: 
[utsushi.desktop.txt](https://github.com/utsushi/utsushi/files/1066157/utsushi.desktop.txt)
https://vimeo.com/221111311

I have tried changing the desktop file exec entry to utsushi-scan-gtkmm but the same issue persists.

**Comment by paddy-hack** [comment]
The desktop file is not included in the utsushi sources.  It must be something that has been added to the binary packages provided by [EPSON](http://download.ebz.epson.net/dsc/search/01/search/?OS=Linux) or your distribution.  The desktop file you attached looks like a perfectly fine [Desktop entry file](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/).  Please contact your distribution's binary package maintainer or EPSON about this.
