### ISSUE TITLE
ES-200 "Operation not supported" with sane

### ISSUE THREAD

**Issue by coaxial** [utsushi/utsushi#33]
I followed the instructions in the README, compiled from source on Ubuntu 17.04, using sane 1.0.25.

after configuring and make install, scanimage -L sees the scanner as ES-200. But scanimage -A or -T both fail.

If I use the instructions at the end of the README, same thing:
```
$ srcdir=. SANE_CONFIG_DIR=. ./libtool --mode=execute -dlopen ./sane/libsane-utsushi.la scanimage -L
device `utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:14.0/usb4/4-2/4-2:1.0' is a EPSON ES-200 

$ srcdir=. SANE_CONFIG_DIR=. ./libtool --mode=execute -dlopen ./sane/libsane-utsushi.la scanimage -A
scanimage: open of device utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:14.0/usb4/4-2/4-2:1.0 failed: Operation not supported

$ srcdir=. SANE_CONFIG_DIR=. ./libtool --mode=execute -dlopen ./sane/libsane-utsushi.la scanimage -T
scanimage: open of device utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:14.0/usb4/4-2/4-2:1.0 failed: Operation not supported
```

Where do I go from here?

**Comment by paddy-hack** [comment]
The `-A` and `-T` require read/write access to the device, unlike the `-L` option.  I suspect a permissions issue so try prefixing your commands with `sudo` like so
``` sh
sudo scanimage -A
```
If that works, my guess is that `utsushi`'s `udev` rules didn't get installed.  These do get installed by default so unless you used the `--disable-udev-config` option (or the equivalent `--enable-udev-config=no`), you should have an `utsushi-esci.rules` file in `/etc/udev/rules/`.  If you don't, try rerunning `sudo make -C drivers/esci install-exec` (preferred) or ` sudo cp drivers/esci/utsushi-esci.rules /etc/udev/rules.d/`.

Note that you need to re-plug (or power-cycle) the device for these rules to take effect after a `sudo make install`.

**Comment by paddy-hack** [comment]
Did my comment from 2017-09-26 fix things for you?  If so, please close.  If not, you may want to try the latest version and have a look at #51.

**Comment by coaxial** [comment]
Thank you, I don't remember how I solved it and I don't have the scanner anymore. But I remember it was finicky, i.e. works for a while then doesn't anymore, and then again. I didn't keep the scanner because the inconsistency made it hard to use.
