### ISSUE TITLE
utsushi can't save a scanned document

### ISSUE THREAD

**Issue by crom5** [utsushi/utsushi#37]
- fully updated Solus on Asus G752VS laptop;
- Epson L365 printer/scanner
- utsushi 3.30.0

Hello,
during the scan the file is there in choosen folder and I can even check its properties/permissions. After the scan the file vanishes.
I've made a short video of what exactly happens:
[http://cromalternativemoney.org/slike/video_epson_scan.mp4](url)

I also tried to run in terminal both "utsushi" and "sudo utsushi" but utsushi doesn't save the scanned png/pdf in any choosen folder.
I would very much appreciate any help in solving this annoying problem.

**Comment by crom5** [comment]
Here's some additional useful info:

    $ lsusb
    Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
    Bus 001 Device 004: ID 0b05:1837 ASUSTek Computer, Inc.
    Bus 001 Device 003: ID 04d9:a070 Holtek Semiconductor, Inc.
    Bus 001 Device 005: ID 04b8:08d2 Seiko Epson Corp.
    Bus 001 Device 002: ID 0bda:57fa Realtek Semiconductor Corp.
    Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub


    $ ls -al /dev/bus/usb/001/005
    crw-rw-rw-+ 1 root root 189, 4 Oct 30 15:10 /dev/bus/usb/001/005


    $ sane-find-scanner

        sane-find-scanner will now attempt to detect your scanner. If the
        result is different from what you expected, first make sure your
        scanner is powered up and properly connected to your computer.
        No SCSI scanners found. If you expected something different, make sure that
        you have loaded a kernel SCSI driver for your SCSI adapter.
        Also you need support for SCSI Generic (sg) in your operating system.
        If using Linux, try "modprobe sg".

        could not open USB device 0x1d6b/0x0003 at 002:001: Access denied (insufficient permissions) could not open USB device 0x0b05/0x1837 at 001:005: Access denied (insufficient permissions) could not open USB device 0x04d9/0xa070 at 001:004: Access denied (insufficient permissions) could not fetch string descriptor: Pipe error could not fetch string descriptor: Pipe error found USB scanner (vendor=0x04b8, product=0x08d2) at libusb:001:003 could not open USB device 0x0bda/0x57fa at 001:002: Access denied (insufficient permissions) could not open USB device 0x1d6b/0x0002 at 001:001: Access denied (insufficient permissions)
        Your USB scanner was (probably) detected. It may or may not be supported by
        SANE. Try scanimage -L and read the backend's manpage.
        Not checking for parallel port scanners.
        Most Scanners connected to the parallel port or other proprietary ports
        can't be detected by this program.
        You may want to run this program as root to find all devices. Once you
        found the scanner devices, be sure to adjust access permissions as
        necessary


    $ sudo sane-find-scanner
    Password:

        sane-find-scanner will now attempt to detect your scanner. If the
        result is different from what you expected, first make sure your
        scanner is powered up and properly connected to your computer.
        No SCSI scanners found. If you expected something different, make sure that
        you have loaded a kernel SCSI driver for your SCSI adapter.
        Also you need support for SCSI Generic (sg) in your operating system.
        If using Linux, try "modprobe sg".

        could not fetch string descriptor: Pipe error could not fetch string descriptor: Pipe error could not fetch string descriptor: Pipe error could not fetch string descriptor: Pipe error found USB scanner (vendor=0x04b8, product=0x08d2) at libusb:001:003
        Your USB scanner was (probably) detected. It may or may not be supported by
        SANE. Try scanimage -L and read the backend's manpage.
        Not checking for parallel port scanners.
        Most Scanners connected to the parallel port or other proprietary ports
        can't be detected by this program.


    $ scanimage -L
    device `v4l:/dev/video0' is a Noname USB2.0 HD UVC WebCam: USB2.0 HD virtual device
    device `utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-5/1-5:1.0' is a EPSON EPSON_L365_Series

**Comment by paddy-hack** [comment]
Sorry for the late follow-up.

It took a couple of minutes to watch the 38s video :wink: but I am pretty sure this happens because the scan logic detects some kind of error (or no images were scanned).  There is code that (silently) removes the output file in that case.

You can try working around this by using `scanimage` or any other SANE frontend.  Those should not be affected by this logic.  Depending on the frontend, you may not be able to save the result as a PNG or PDF file, though.

That said, if there really was an error, you may end up with a broken image file.

If you want to dig into why this happens, you'll have to change the `lib/log.cpp` file a bit and recompile Utsushi.  Unfortunately, you cannot change the log levels without a recompile 😞 

Replace
``` cpp
log::priority log::threshold = log::FATAL;
log::category log::matching  = log::NOTHING;
```
with
``` cpp
log::priority log::threshold = log::DEBUG;
log::category log::matching  = log::ALL;
```
for maximum output.  Start `utsushi` from the command-line and redirect standard error to a file, like so
``` sh
utsushi 2> log.txt
```

You can **attach** the log here and I'll take a look.

**Comment by rentaclaus** [comment]
I have a similar problem. No scanned image is saved (regardless what type, pdf, pnm, tiff ...). It happens on Ubuntu 17.04 and 17.10 (verified on two machines, all 64-bit). I tried Imagescan 3.28 ... 3.33

Device is a Epson XP-540

Lsub
Bus 003 Device 006: ID 04b8:1117 Seiko Epson Corp.

Normally it is attached via Wlan
scanimage -L
device `imagescan:esci:networkscan://192.168.50.24:1865' is a Epson XP-540

Xsane, scanimage, simple-scan work fine

**Comment by crom5** [comment]
Hi paddy-hack, thank you very much for your reply.

Within Solus menu I have 3 scan applications: "Simple Scan", "Image Scan! for Linux" and "Epson Image Scan". I don't know what are other SANE frontend applications or if they even exist within Solus repository?
Unfortunately I'm not capable to recompile Utsushi by myself, and file "log.cpp" doesn't exist inside my Solus.

Here's some more useful info from my first tryings:

```
**Simple scan**

*
I can select the Epson L365 in scan source. When I press the button "scan", usual rotating circles appears for 2 seconds and that's it, nothing happens later - scanner is completely dead.

*
terminal command "simple-scan": I can select the Epson L365 in scan source. When I press the button "scan", usual rotating circles appears for 2 seconds and that's it, nothing happens later - scanner is completely dead. Nothing appears in terminal.

*
terminal command "sudo simple-scan": I can select the Epson L365 in scan source. When I press the button "scan", usual rotating circles appears for 2 seconds and that's it, nothing happens later - scanner is completely dead.
```

```
**iscan**

*
I get the error message: "Could not send command to scanner. Check the scanner's status."

*
terminal command "iscan": I get the error message "Could not send command to scanner. Check the scanner's status." This is what I get in terminal:

*
$ iscan
(iscan:1215): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(iscan:1215): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(iscan:1215): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

*
terminal command "sudo iscan": I get the error message "Could not send command to scanner. Check the scanner's status." This is what I get in terminal:

$ sudo iscan
Password:
(iscan:1249): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(iscan:1249): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(iscan:1249): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
```

```
**utsushi 3.32.0-3**

*
scan itself is processing, but no image is saved and also no error occurs.

*
terminal command "utsushi": scan itself is processing, but no image is saved. This is what I get in terminal:

$ utsushi
(utsushi-scan-gtkmm:1181): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(utsushi-scan-gtkmm:1181): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(utsushi-scan-gtkmm:1181): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

*
terminal command "sudo utsushi": scan itself is processing, but no image is saved. This is what I get in terminal:

sudo utsushi
Password:
(utsushi-scan-gtkmm:1278): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(utsushi-scan-gtkmm:1278): Gtk-WARNING : Unable to locate theme engine in module_path: "murrine",
(utsushi-scan-gtkmm:1278): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
```

Consequently I installed via Software center "gtk2-engine-murrine" and "gtk2-engine-murrine-32bit".
After restarting, I tried to launch all 3 programs via terminal, but it still doesn't work. The only difference is that now my terminal is empty without any Gtk-WARNING.

**Comment by rentaclaus** [comment]
I compiled now utsushi by my own. And big surprise: the image is saved ... (see attach)
![unbenannt](https://user-images.githubusercontent.com/33800217/32996013-516e7fdc-cd7d-11e7-8a14-8761d0050853.jpeg)


Nevertheless the output of utsushi 2> log.txt
[log.txt](https://github.com/utsushi/utsushi/files/1486027/log.txt)

Unfortunately it recognizes my scanner only when attached via usb ( no network, but I'm sure thats only a matter of configuration)

A big hug to

paddy-hack

**Comment by rentaclaus** [comment]
After copying networkscan to the correct directory (/usr/local/libexec/utsushi in my case) and placing a proper utsushi.conf in '/usr/local/etc/utsushi' networkscaning is also fine now.

Many thanks once more

**Comment by crom5** [comment]
One of the Solus developers recompiled utsushi for me, so here's the entire content of a file "log.txt" generated after executing terminal command "utsushi 2> log.txt":

```
2017-Nov-22 11:09:37.981947[140441565353408]: /etc/utsushi/utsushi.conf: no such file
2017-Nov-22 11:09:37.982091[140441565353408]: no such file: /etc/utsushi/utsushi.conf
2017-Nov-22 11:09:38.047781[140441565353408]: some device not found. delete combo::?adf=esci:usb:04b8:0155&fb=esci:gt-s650:usb:04b8:013c
2017-Nov-22 11:09:38.048299[140441565353408]: some device not found. delete combo::?adf=esci:usb:04b8:0156&fb=esci:gt-s650:usb:04b8:013c
2017-Nov-22 11:09:38.048809[140441565353408]: some device not found. delete combo::?adf=esci:usb:04b8:0157&fb=esci:gt-s650:usb:04b8:013c
2017-Nov-22 11:09:38.049200[140441565353408]: some device not found. delete combo::?adf=esci:usb:04b8:0155&fb=esci:gt-s650:usb:04b8:013d
2017-Nov-22 11:09:38.049589[140441565353408]: some device not found. delete combo::?adf=esci:usb:04b8:0156&fb=esci:gt-s650:usb:04b8:013d
2017-Nov-22 11:09:38.049977[140441565353408]: some device not found. delete combo::?adf=esci:usb:04b8:0157&fb=esci:gt-s650:usb:04b8:013d
2017-Nov-22 11:09:38.113684[140441565353408]: looking for preloaded 'esci' driver
2017-Nov-22 11:09:38.113813[140441565353408]: looking for 'esci' driver in '/usr/lib64/utsushi'
2017-Nov-22 11:09:38.119803[140441565353408]: using '/usr/lib64/utsushi/libdrv-esci'
2017-Nov-22 11:09:38.122551[140441565353408]: does not appear to be an ESC/I-2 device (invalid command)
2017-Nov-22 11:09:38.128773[140441565353408]: detected a 'PID 08D2'
2017-Nov-22 11:09:38.168632[140441565353408]: no software resolution options
2017-Nov-22 11:09:38.175065[140441565353408]: failure checking tesseract version: Resource temporarily unavailable
2017-Nov-22 11:09:38.181542[140441565353408]: failure checking for tesseract language pack: Resource temporarily unavailable
2017-Nov-22 11:09:38.181943[140441565353408]: update the set of controllers
2017-Nov-22 11:09:38.198514[140441565353408]: update controller visibility
2017-Nov-22 11:09:49.340703[140441286579968]: assuming top-to-bottom scan direction
2017-Nov-22 11:09:51.387937[140441286579968]: assuming top-to-bottom scan direction
2017-Nov-22 11:09:51.399215[140441286579968]: found GraphicsMagick-1.3.26
2017-Nov-22 11:09:51.399820[140441286579968]: shell-pipe: buffer size now 65536 octets
2017-Nov-22 11:09:51.399860[140441286579968]: gm convert started (pid: 1572)
2017-Nov-22 11:09:51.399885[140441286579968]: invocation: gm convert  -size 637x877 -depth 8 -density 75x75 -units PixelsPerInch - -density 75x75 -recolor "1.0782 0.0135 -0.091700000000000004 0.0206 1.0983000000000001 -0.11890000000000001 0.011299999999999999 -0.14849999999999999 1.1372 " -orient top-left -auto-orient jpeg:-
2017-Nov-22 11:10:08.867019[140441286579968]: assuming top-to-bottom scan direction
2017-Nov-22 11:10:08.868777[140441286579968]: gm convert (pid: 1572): gm convert: No decode delegate for this image format (/tmp/gmHDnUJI).
[log.txt](https://github.com/utsushi/utsushi/files/1495555/log.txt)


2017-Nov-22 11:10:08.873181[140441286579968]: gm convert exited (pid: 1572, status: 1)
2017-Nov-22 11:10:08.873259[140441286579968]: assuming top-to-bottom scan direction
2017-Nov-22 11:10:08.873304[140441286579968]: file_odevice::write(): Bad file descriptor
2017-Nov-22 11:10:08.873349[140441286579968]: removing /home/aljosa/Documents/Untitled.pdf because no images were produced
2017-Nov-22 11:10:08.873407[140441286579968]: No such file or directory
```

**Comment by crom5** [comment]
**utsushi can't save a scanned document - Problem solved:**
https://solus-project.com/forums/viewtopic.php?f=9&t=7826&start=30

**Comment by paddy-hack** [comment]
@crom5 Glad your problem is solved 😄

Looks like your issue was caused by GraphicsMagick not knowing how to decode JPEG images.  How odd 😮
