### ISSUE TITLE
updated de.po

### ISSUE THREAD

**Issue by rentaclaus** [utsushi/utsushi#40]
Attached is an updated de.po.

I translated to my best knowledge (I'm a native speaker and studied amongst others German-Literature). But I was not able to translate everthing. In some cases the 'real thing' is needed, means seeing the device and the app in action ... to understand what is happening and to find a proper translation.
I also corrected the existing translation when it was misleading (e.g. 'zoom in' is not 'Zoom ein', it means that the pre-scanned image is enlarged in the GUI, so I translated it to 'Vorschau vergrößern' = 'enlarge  pre-view'
[de.zip](https://github.com/utsushi/utsushi/files/1506958/de.zip)

Use it or thrash it. It's all your decision ...

**Comment by paddy-hack** [comment]
Thanks!  Not sure how to put you in the "Last-Translator:" field of the po file, going with `rentaclaus` for now.  If you want something else, let me know (by direct mail if you prefer, you know my address).

I'll take your German translations as is.  I have studied German for five years in secondary school but I will not be second guessing your native skills :wink:

As for the missing context needed for translation, I'll be happy to add some where possible.  I guess I could start with the ones you didn't translate or left as fuzzy.  The way that works is by adding source code comments that `gettext` will pick up and dump in the `*.po` files.

As for the "sucky" translations 😢, I guess we will have to "blame" that on the upstream translators.  I realize they often don't have all the necessary information to do the best job they can (and may be pressed for time as well) but sometimes upstream translations make you cringe (e.g. when there are obvious, for a native speaker, spelling mistakes 😱).

**Comment by rentaclaus** [comment]
Nobody needs to be 'blamed'. Translating is a delicate task. Knowing the language isn't enough. Meanings are produced by the context in which the words are (in linguistic: the indexicality of words and meanings ). And german is extra difficult for foreigners (I'm working with refugees), even most germans don't speak correct german ;-).

**Comment by paddy-hack** [comment]
> Nobody needs to be 'blamed'.

"attributed", all right.  I used got used to calling it "blamed" courtesy of `git blame` 😉
