### ISSUE TITLE
utsushi doesn't detect device anymore when hot-plugged

### ISSUE THREAD

**Issue by m1027** [utsushi/utsushi#41]
utsushi (utsushi list) does not detect the DS-1630 anymore if the device is
hot-plugged.

If the device is cold-plugged (connected before boot) detection and scanning
work as expected.

Some more hints:

dmesg lists the device in both cases as usual.

Things were working some weeks ago (at max in august).

Changes were: Recent pulls from this utsushi repository, linux kernel updated
from 4.13.x to 4.14.x, systemd update to 235.

And there is a similar issue listed: https://github.com/utsushi/utsushi/issues/36

**Comment by paddy-hack** [comment]
It would be very helpful if you could tell me what Utsushi version (as in approximate git commit hash) you were using when things worked.  The `systemd` version when things worked will also help a lot.  If you could also tell me what version of which distribution you're using that'd be 👍.

As to #36, that's a FreeBSD story, where devices haven't been detected since the beginning so it's extremely unlikely to be related 😉

**Comment by m1027** [comment]
Sure, here more information:

utsushi commit:

The commit that did most probably still work is from 2017-08-20:

commit 0186ead6c663b9d37b48cd3c6f68ee89e9b0eb5f
Author:     Olaf Meeuwissen
AuthorDate: Sun Aug 20 14:05:46 2017 +0900
Commit:     Olaf Meeuwissen
CommitDate: Sun Aug 20 14:05:46 2017 +0900

    Add model name for the previously added models

After that there are no commits for some time, only in october where
things might have been broken already.

systemd:

The current version of system is 235 while the previous might have
been either 233 or 234 but probably already 234 or 235.

linux:

I am using gentoo linux / rolling versioning / compiling everything
and always from source.

Some more pointers:

As utsushi is not present among gentoo's packages I am using a gentoo packet
description (ebuild) from this overlay repository which basically pull's stuff
from your repo:

https://github.com/sirjaren/gentoo-overlay

In case you cannot reproduce this hotplug issue and need me to dissect the
misbehaviour by trying other utsushi commits let me know. I might find some
time to set up my own utsushi overlay and give that a try.

**Comment by paddy-hack** [comment]
Hmm, the changelog is mostly just integrating the upstream changes from `imagescan`, adding logically required header files (that are not implicitly included on FreeBSD) and a symbol export.  Nothing that would affect the device hot-plugging detection.

Feel free to attempt dissecting but I think that the problem is caused by your upgrades of the kernel and/or systemd.  Perhaps you should first try reverting those, one at a time, to see if that fixes your hotplugging issue.  Once we know which of utsushi, the kernel and systemd triggers the behaviour you're reporting, we stand a better chance of fixing it.

**Comment by m1027** [comment]
Thanks, luckily I had a backup of kernel-4.13.12. Keeping recent utsushi and
systemd but downgrading to that older kernel, hotplugging works again.

Below you'll find the diff of the config files of my kernels 4.13.12 and
4.14.3. The config files show slightly older kernel versions because I do not
recreate them for minor kernel updates. In case you detect something relevant
let me know. Hm...

```diff
< # Linux/x86 4.13.9 Kernel Configuration
---
> # Linux/x86 4.14.2 Kernel Configuration
97d96
< # CONFIG_IRQ_DOMAIN_DEBUG is not set
100d98
< # CONFIG_GENERIC_IRQ_DEBUGFS is not set
211a210
> CONFIG_FUTEX_PI=y
238a238
> # CONFIG_SLAB_FREELIST_HARDENED is not set
242d241
< CONFIG_TRACEPOINTS=y
246c245
< CONFIG_UPROBES=y
---
> # CONFIG_UPROBES is not set
272a272
> CONFIG_HAVE_RCU_TABLE_FREE=y
294a295
> CONFIG_HAVE_MOD_ARCH_SPECIFIC=y
318d318
< # CONFIG_GCOV_KERNEL is not set
336d335
< # CONFIG_BLK_DEBUG_FS is not set
402c401
< # CONFIG_INTEL_RDT_A is not set
---
> # CONFIG_INTEL_RDT is not set
410d408
< # CONFIG_IOSF_MBI_DEBUG is not set
456d453
< # CONFIG_X86_MCE_INJECT is not set
473a471
> # CONFIG_X86_5LEVEL is not set
476a475,476
> CONFIG_ARCH_HAS_MEM_ENCRYPT=y
> # CONFIG_AMD_MEM_ENCRYPT is not set
568a569
> CONFIG_ARCH_HAS_ADD_PAGES=y
621d621
< # CONFIG_ACPI_CUSTOM_METHOD is not set
860d859
< # CONFIG_NETFILTER_DEBUG is not set
1086a1086
> # CONFIG_NET_NSH is not set
1097a1098
> # CONFIG_BPF_STREAM_PARSER is not set
1104d1104
< # CONFIG_NET_DROP_MONITOR is not set
1139d1138
< # CONFIG_IRDA is not set
1150d1148
< # CONFIG_CFG80211_DEBUGFS is not set
1164d1161
< # CONFIG_MAC80211_DEBUGFS is not set
1233d1229
< # CONFIG_BLK_CPQ_CISS_DA is not set
1485a1482,1483
> CONFIG_NET_VENDOR_HUAWEI=y
> # CONFIG_HINIC is not set
1568a1567
> # CONFIG_ROCKCHIP_PHY is not set
1638d1636
< CONFIG_IWLWIFI_DEVICE_TRACING=y
2136,2139d2133
< 
< #
< # Broadcom specific AMBA
< #
2148a2143
> # CONFIG_MFD_BD9571MWV is not set
2204a2200
> # CONFIG_MFD_TPS68470 is not set
2221a2218
> # CONFIG_RC_CORE is not set
2819d2815
< # CONFIG_MMC_DEBUG is not set
2827a2824
> # CONFIG_MMC_DEBUG is not set
3010a3008
> # CONFIG_ALTERA_MSGDMA is not set
3030d3027
< # CONFIG_SW_SYNC is not set
3158a3156,3159
> # Amlogic SoC drivers
> #
> 
> #
3164a3166,3169
> 
> #
> # Qualcomm SoC drivers
> #
3204,3207d3208
< 
< #
< # FPGA Configuration Support
< #
3347d3347
< CONFIG_NFS_DEBUG=y
3358c3358
< CONFIG_SUNRPC_DEBUG=y
---
> # CONFIG_SUNRPC_DEBUG is not set
3435d3434
< # CONFIG_DYNAMIC_DEBUG is not set
3445c3444
< CONFIG_DEBUG_FS=y
---
> # CONFIG_DEBUG_FS is not set
3449,3451c3448
< CONFIG_ARCH_WANT_FRAME_POINTERS=y
< # CONFIG_FRAME_POINTER is not set
< # CONFIG_STACK_VALIDATION is not set
---
> CONFIG_STACK_VALIDATION=y
3489c3486
< CONFIG_STACKTRACE=y
---
> # CONFIG_STACKTRACE is not set
3500d3496
< CONFIG_NOP_TRACER=y
3509,3513d3504
< CONFIG_TRACE_CLOCK=y
< CONFIG_RING_BUFFER=y
< CONFIG_EVENT_TRACING=y
< CONFIG_CONTEXT_SWITCH_TRACER=y
< CONFIG_TRACING=y
3515,3536c3506,3508
< CONFIG_FTRACE=y
< # CONFIG_FUNCTION_TRACER is not set
< # CONFIG_IRQSOFF_TRACER is not set
< # CONFIG_SCHED_TRACER is not set
< # CONFIG_HWLAT_TRACER is not set
< # CONFIG_ENABLE_DEFAULT_TRACERS is not set
< # CONFIG_FTRACE_SYSCALLS is not set
< # CONFIG_TRACER_SNAPSHOT is not set
< CONFIG_BRANCH_PROFILE_NONE=y
< # CONFIG_PROFILE_ANNOTATED_BRANCHES is not set
< # CONFIG_PROFILE_ALL_BRANCHES is not set
< # CONFIG_STACK_TRACER is not set
< # CONFIG_BLK_DEV_IO_TRACE is not set
< CONFIG_UPROBE_EVENTS=y
< CONFIG_BPF_EVENTS=y
< CONFIG_PROBE_EVENTS=y
< # CONFIG_MMIOTRACE is not set
< # CONFIG_HIST_TRIGGERS is not set
< # CONFIG_TRACEPOINT_BENCHMARK is not set
< # CONFIG_RING_BUFFER_BENCHMARK is not set
< # CONFIG_RING_BUFFER_STARTUP_TEST is not set
< # CONFIG_TRACE_EVAL_MAP_FILE is not set
---
> # CONFIG_FTRACE is not set
> # CONFIG_PROVIDE_OHCI1394_DMA_INIT is not set
> # CONFIG_DMA_API_DEBUG is not set
3541d3512
< # CONFIG_LKDTM is not set
3551,3552d3521
< # CONFIG_PROVIDE_OHCI1394_DMA_INIT is not set
< # CONFIG_DMA_API_DEBUG is not set
3584a3554,3555
> # CONFIG_FRAME_POINTER_UNWINDER is not set
> CONFIG_ORC_UNWINDER=y
3807c3778
< CONFIG_BINARY_PRINTF=y
---
> # CONFIG_BINARY_PRINTF is not set
3838a3810
> CONFIG_XXHASH=y
3844a3817,3818
> CONFIG_ZSTD_COMPRESS=y
> CONFIG_ZSTD_DECOMPRESS=y
3876d3849
< CONFIG_ARCH_HAS_MMIO_FLUSH=y
3877a3851
> # CONFIG_STRING_SELFTEST is not set
```

**Comment by pat42smith** [comment]
I am also seeing this problem.

Scanner: ES-400
OS: Arch Linux
systemd: 235.38-4
utsushi: built from source in http://support.epson.net/linux/src/scanner/imagescanv3/fedora/imagescan-3.33.0-1epson4fedora27.src.rpm, using the instructions at https://aur.archlinux.org/packages/imagescan/ (see the link to the PKGBUILD file at the top right of that page)

With the 4.13.12 version of the kernel, hot-plugging works. With 4.14.3 (or 4.14.5), it does not work.

After hot-plugging, although scanimage -L does not see the scanner, sane-find-scanner does see it, reporting:

found USB scanner (vendor=0x04b8 [EPSON], product=0x0156 [ES-400]) at libusb:002:002

**Comment by m1027** [comment]
I suspect that something goes wrong below /sys/devices/ after re-plugging.

Normal output is somthing like this:

utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:1c.6/0000:0e:00.0/usb4/4-1/4-1:1.0

Not sure in this area but it seems to me that 4.14.x keeps kind of a ghost
entry for the previously attached scanner and adds another for the current.

And maybe this confuses utsushi?

It would be helpful to get hints from the utsushi maintainer on how the
algorithm tries to detect plugged scanners.

**Comment by paddy-hack** [comment]
OK, so we have two distributions that display the same symptom and it seems to narrow down to a kernel upgrade, from 4.13.12 to 4.14.3.

The fact that `sane-find-scanner` sees the device only means that it thinks there is a scanner attached.  It says *nothing* about whether there's a SANE backend, e.g. `utsushi`, that knows how to communicate with it.

The `utsushi` code detects its supported scanners by looking for an `utsushi_driver` device property in the information provided by `udev`.  The property holds the name of the driver to use, i.c. `esci`.  It might help if you could attach the output of `sudo udevadm info -e` before, shortly after and a couple of minutes (to give `udev` time to settle) after hot-plugging the device.

**Comment by pat42smith** [comment]
I've attached 3 files showing outputs of sudo udevadm info -e.
u0: before hot-plugging
u1: after
u2: a couple of minutes later

**Comment by m1027** [comment]
Results of a slightly different test:

Scanner connected to gentoo system with kernel 4.14.6, then booting.

Scanner detected by utsushi list as:
utsushi:esci:usb:/sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.0

Test scan works. 

Output of `udevadm info -e`:

```
P: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2
N: bus/usb/001/003
E: BUSNUM=001
E: DEVNAME=/dev/bus/usb/001/003
E: DEVNUM=003
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_FOR_SEAT=usb-pci-0000_00_1a_0-usb-0_1_2
E: ID_MODEL=DS-1630
E: ID_MODEL_ENC=DS-1630
E: ID_MODEL_ID=015c
E: ID_PATH=pci-0000:00:1a.0-usb-0:1.2
E: ID_PATH_TAG=pci-0000_00_1a_0-usb-0_1_2
E: ID_REVISION=0100
E: ID_SERIAL=EPSON_DS-1630_583256573030363336
E: ID_SERIAL_SHORT=583256573030363336
E: ID_USB_INTERFACES=:ffffff:ffaa01:
E: ID_VENDOR=EPSON
E: ID_VENDOR_ENC=EPSON
E: ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
E: ID_VENDOR_ID=04b8
E: MAJOR=189
E: MINOR=2
E: PRODUCT=4b8/15c/100
E: SUBSYSTEM=usb
E: TAGS=:seat:uaccess:
E: TYPE=0/0/0
E: USEC_INITIALIZED=2192894
E: libsane_matched=yes
E: utsushi_driver=esci
```

Unplugging and re-plugging usb.
utsushi list does not detect the scanner.

Output of `udevadm info -e`:

```
P: /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2
N: bus/usb/001/004
E: BUSNUM=001
E: DEVNAME=/dev/bus/usb/001/004
E: DEVNUM=004
E: DEVPATH=/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2
E: DEVTYPE=usb_device
E: DRIVER=usb
E: ID_BUS=usb
E: ID_MODEL=DS-1630
E: ID_MODEL_ENC=DS-1630
E: ID_MODEL_ID=015c
E: ID_REVISION=0100
E: ID_SERIAL=EPSON_DS-1630_583256573030363336
E: ID_SERIAL_SHORT=583256573030363336
E: ID_USB_INTERFACES=:ffffff:ffaa01:
E: ID_VENDOR=EPSON
E: ID_VENDOR_ENC=EPSON
E: ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
E: ID_VENDOR_ID=04b8
E: MAJOR=189
E: MINOR=3
E: PRODUCT=4b8/15c/100
E: SUBSYSTEM=usb
E: TYPE=0/0/0
E: USEC_INITIALIZED=23387757829
```

Here, `libsane_matched=yes` and `utsushi_driver=esci` are missing.

**Comment by pat42smith** [comment]
I've found something that seems interesting, although that may just reflect my ignorance.

After booting with the scanner already powered on, `/run/udev/data/c189:129` contains the line `E:libsane_matched=yes`. After hot-plugging, this line, and a few others, are missing from that file.

However, if I use `udevadm monitor -p` to see the events created when I hot-plug the scanner, the output includes the line `libsane_matched=yes`. Could this indicate that udev actually realizes there is a SANE driver for this scanner, but somehow fails to update the database and the files under /run?

More details...

`/run/udev/data/c189:129` after cold-plugging:
```
I:8984298
E:ID_VENDOR=EPSON
E:ID_VENDOR_ENC=EPSON
E:ID_VENDOR_ID=04b8
E:ID_MODEL=ES-400
E:ID_MODEL_ENC=ES-400
E:ID_MODEL_ID=0156
E:ID_REVISION=0100
E:ID_SERIAL=EPSON_ES-400_583248383033393411
E:ID_SERIAL_SHORT=583248383033393411
E:ID_BUS=usb
E:ID_USB_INTERFACES=:ffffff:ffaa01:
E:libsane_matched=yes
E:ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
E:ID_PATH=pci-0000:00:14.0-usb-0:2
E:ID_PATH_TAG=pci-0000_00_14_0-usb-0_2
E:ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_2
E:utsushi_driver=esci
G:uaccess
G:seat
```

`/run/udev/data/c189:129` after hot-plugging:
```
I:73378900
E:ID_VENDOR=EPSON
E:ID_VENDOR_ENC=EPSON
E:ID_VENDOR_ID=04b8
E:ID_MODEL=ES-400
E:ID_MODEL_ENC=ES-400
E:ID_MODEL_ID=0156
E:ID_REVISION=0100
E:ID_SERIAL=EPSON_ES-400_583248383033393411
E:ID_SERIAL_SHORT=583248383033393411
E:ID_BUS=usb
E:ID_USB_INTERFACES=:ffffff:ffaa01:
E:ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
```

Output of `udevadm monitor -p` while hot-plugging:
```
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[73.363285] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2 (usb)
ACTION=add
BUSNUM=002
DEVNAME=/dev/bus/usb/002/002
DEVNUM=002
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2
DEVTYPE=usb_device
MAJOR=189
MINOR=129
PRODUCT=4b8/156/100
SEQNUM=2835
SUBSYSTEM=usb
TYPE=0/0/0

KERNEL[73.372175] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0
DEVTYPE=usb_interface
INTERFACE=255/255/255
MODALIAS=usb:v04B8p0156d0100dc00dsc00dp00icFFiscFFipFFin00
PRODUCT=4b8/156/100
SEQNUM=2836
SUBSYSTEM=usb
TYPE=0/0/0

KERNEL[73.374194] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.1 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.1
DEVTYPE=usb_interface
INTERFACE=255/170/1
MODALIAS=usb:v04B8p0156d0100dc00dsc00dp00icFFiscAAip01in01
PRODUCT=4b8/156/100
SEQNUM=2837
SUBSYSTEM=usb
TYPE=0/0/0

KERNEL[73.374398] bind     /devices/pci0000:00/0000:00:14.0/usb2/2-2 (usb)
ACTION=bind
BUSNUM=002
DEVNAME=/dev/bus/usb/002/002
DEVNUM=002
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2
DEVTYPE=usb_device
DRIVER=usb
MAJOR=189
MINOR=129
PRODUCT=4b8/156/100
SEQNUM=2838
SUBSYSTEM=usb
TYPE=0/0/0

UDEV  [73.382911] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2 (usb)
ACTION=add
BUSNUM=002
DEVNAME=/dev/bus/usb/002/002
DEVNUM=002
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2
DEVTYPE=usb_device
DRIVER=usb
ID_BUS=usb
ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_2
ID_MODEL=ES-400
ID_MODEL_ENC=ES-400
ID_MODEL_ID=0156
ID_PATH=pci-0000:00:14.0-usb-0:2
ID_PATH_TAG=pci-0000_00_14_0-usb-0_2
ID_REVISION=0100
ID_SERIAL=EPSON_ES-400_583248383033393411
ID_SERIAL_SHORT=583248383033393411
ID_USB_INTERFACES=:ffffff:ffaa01:
ID_VENDOR=EPSON
ID_VENDOR_ENC=EPSON
ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
ID_VENDOR_ID=04b8
MAJOR=189
MINOR=129
PRODUCT=4b8/156/100
SEQNUM=2835
SUBSYSTEM=usb
TAGS=:uaccess:seat:
TYPE=0/0/0
USEC_INITIALIZED=73378900
libsane_matched=yes
utsushi_driver=esci

UDEV  [73.384269] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0
DEVTYPE=usb_interface
ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
INTERFACE=255/255/255
MODALIAS=usb:v04B8p0156d0100dc00dsc00dp00icFFiscFFipFFin00
PRODUCT=4b8/156/100
SEQNUM=2836
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=73383947
adb_user=yes

UDEV  [73.385371] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.1 (usb)
ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.1
DEVTYPE=usb_interface
ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
INTERFACE=255/170/1
MODALIAS=usb:v04B8p0156d0100dc00dsc00dp00icFFiscAAip01in01
PRODUCT=4b8/156/100
SEQNUM=2837
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=73385047
adb_user=yes

UDEV  [73.386734] bind     /devices/pci0000:00/0000:00:14.0/usb2/2-2 (usb)
ACTION=bind
BUSNUM=002
DEVNAME=/dev/bus/usb/002/002
DEVNUM=002
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-2
DEVTYPE=usb_device
DRIVER=usb
ID_BUS=usb
ID_MODEL=ES-400
ID_MODEL_ENC=ES-400
ID_MODEL_ID=0156
ID_REVISION=0100
ID_SERIAL=EPSON_ES-400_583248383033393411
ID_SERIAL_SHORT=583248383033393411
ID_USB_INTERFACES=:ffffff:ffaa01:
ID_VENDOR=EPSON
ID_VENDOR_ENC=EPSON
ID_VENDOR_FROM_DATABASE=Seiko Epson Corp.
ID_VENDOR_ID=04b8
MAJOR=189
MINOR=129
PRODUCT=4b8/156/100
SEQNUM=2838
SUBSYSTEM=usb
TYPE=0/0/0
USEC_INITIALIZED=73378900
```

**Comment by paddy-hack** [comment]
@pat42smith I didn't get the attachments.  I think GitHub stripped them out of the mail reply you sent.  Attachments can be added via the web interface.

@m1027, @pat42smith  Those missing key/value pairs are *exactly* the ones Utsushi is looking for when it tries to find supported scanners 😒 

@pat42smith Your `udevadm monitor -p` output is intriguing!  I haven't been doing any device detection stuff lately and had forgotten about the `monitor` subcommand 🤦‍♂️ .  Especially the two entries below, where the first lists the `libsane_matched` and `utsushi_driver` properties and the second does *not* (assuming you copied *all* the output 😉 ).
```
UDEV  [73.382911] add      /devices/pci0000:00/0000:00:14.0/usb2/2-2 (usb)
UDEV  [73.386734] bind     /devices/pci0000:00/0000:00:14.0/usb2/2-2 (usb)
```
My understanding from the manual page is that `udev` rules

> provide additional device information to be stored in the udev database

How come `udev` "forgets" these properties between uevents that are only ~3.8ms and three events apart due to a kernel upgrade?  I'm clueless.  Perhaps you should submit a bug report to your respective distributions' bug tracker for the kernel or look for reports of similar (mis?)behaviour.  I sure would like to find out why this happens.

In the mean time, you could try modifying the installed `utsushi-esci.rules` file so that it also triggers on bind events.  Untried but I think removing the first non-comment line (the one that starts with `ACTION`) will do that trick.

**Comment by pat42smith** [comment]
[u2.txt](https://github.com/utsushi/utsushi/files/1592726/u2.txt)

[u1.txt](https://github.com/utsushi/utsushi/files/1592725/u1.txt)

[u0.txt](https://github.com/utsushi/utsushi/files/1592721/u0.txt)

@paddy-hack Per your suggestion, I just tried commenting out the only line beginning with `ACTION` in `/etc/udev/rules.d/utsushi-esci.rules`, and then rebooting. Hot-plugging now works! Thanks!

Should I consider this just a temporary work-around, or will you be including it in the utsushi source as a permanent fix? Or is it too early to decide that?

I've attached the 3 files I mentioned before, now with .txt extensions so that GitHub will accept them.

**Comment by paddy-hack** [comment]
@pat42smith I would consider it a temporary workaround.  The `ACTION` is in there to improve the speed with which events are processed, just like the two lines following it.  This approach has been copied from the `libsane` package (but that does not require the values to stick around for the time the device is plugged in and powered on).

Thanks for the attachments but unfortunately they don't shed any light on why the `libsane_matched` and `utsushi_driver` device properties disappear.  Would you be able to provide the `udevadm monitor -p` output of hotplugging the device with the 4.13.12 version of the kernel?  Maybe that gives us a clue about what changed.

**Comment by pat42smith** [comment]
[events-4.13.12.txt](https://github.com/utsushi/utsushi/files/1595014/events-4.13.12.txt)

@paddy-hack I've attached the output of `udevadm monitor -p` while hotplugging the scanner under the 4.13.12 kernel. One difference stands out: with 4.13.12, there were no bind events, only add events.

**Comment by paddy-hack** [comment]
In that case, you can probably replace `add` with `bind` for the `ACTION`.

Now, if only I knew what's up with these new(?) bind events and how `udev` handles them.

**Comment by pat42smith** [comment]
Or even `ACTION!="add|bind", GOTO="utsushi_esci_rules_end"`, which works with both 4.14.12 and 4.13.12.
