### ISSUE TITLE
Arch Linux libimagemagick error

### ISSUE THREAD

**Issue by fcgdam** [utsushi/utsushi#43]
I'm using a ET-3750 network connected printer on Arch Linux that uses the 7.07.20 version of libimagemagick. But this rep fails to compile with the following error:
```
doc-locate.cpp: In member function ‘Magick::Geometry {anonymous}::locator::cropdoc() const’:
doc-locate.cpp:265:25: error: ‘class Magick::Geometry’ has no member named ‘xNegative’
       if (clone.page ().xNegative ())
                         ^~~~~~~~~
doc-locate.cpp:269:25: error: ‘class Magick::Geometry’ has no member named ‘yNegative’
       if (clone.page ().yNegative ())
                         ^~~~~~~~~
```
It seems that this version of libimagemagick is not supported?

Any ideas for a work around?

**Comment by paddy-hack** [comment]
Hmm, those API entries were [removed](https://github.com/ImageMagick/ImageMagick/commit/6e6af8ed20baf26aaf110518af6bca24f804cf86#diff-58511ed7aa0b4c91bff380cc4b10691b) and first made available in 7.0.1-0.  That notwithstanding, the [porting guide](https://www.imagemagick.org/script/porting.php) claims

> The Magick++ and PerlMagick API's have not changed and matches that of the ImageMagick version 6.

Current completely untested ideas for workarounds:
 - use GraphicsMagick instead
 - stick with ImageMagick version 6
 - remove the troublesome `if (HAVE_IMAGE_MAGICK_PP)` statement and check if deskewing still works as expected.  The `if`-statement is neither used nor needed with GraphicsMagick.  Maybe ImageMagick version 7 doesn't need it either.

**Comment by fcgdam** [comment]
Sorry for the late answer.  

I'll check if GraphicsMagick can be used since there are dependencies on Arch at least for Cups and Shutter.

**Comment by fcgdam** [comment]
Compilation issue solved with installing libmagick-6 and re running configure.

Still, my et-3750 scanner isn't detected.... but that's another issue.

**Comment by m1027** [comment]
FYI: I successfully recompiled utsushi against imagemagick-7.0.7.19. No compilation errors anymore after the imagemagick patch mentioned in the ebuild of sirjaren.
