### ISSUE TITLE
ET-3750 support

### ISSUE THREAD

**Issue by fcgdam** [utsushi/utsushi#44]
So I'm using the latest sources:

> utsushi  --version
> utsushi (Utsushi) 0.33.0
> Copyright (C) 2012-2015  SEIKO EPSON CORPORATION
> License: GPL-3.0+

But while it detects the scanner it doesn't work :)

On the Readme, this specific mode, the ET-3750 is not listed, so I suppose it's unsupported.

Any ideas for supporting it?

Most of the scantools detect the scanner but then it fails to use it.

**Comment by fcgdam** [comment]
It seems the latest version on Epson Site for Image Scan, version 0.35 supports this scanner now.
Still the Sane support doesn't work, but anyways I can scan now without using the Android app,

**Comment by paddy-hack** [comment]
FWIW, the utsushi sources have been synced with the Image Scan version in d3cb94e.
