### ISSUE TITLE
ES-200 supported?

### ISSUE THREAD

**Issue by mburgess00** [utsushi/utsushi#51]
I am trying to get an ES-200 scanner working with a raspberry pi. I have managed to build utsushi successfully but when I run it I get a "not supported" message. Is the ES-200 in fact not supported?

pi@raspberrypi:/opt $ bin/utsushi 
esci:usb:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0: not supported
pi@raspberrypi:/opt $ scanimage -h
Usage: scanimage [OPTION]...

Start image acquisition on a scanner device and write image data to
standard output.

Parameters are separated by a blank from single-character options (e.g.
-d epson) and by a "=" from multi-character options (e.g. --device-name=epson).
-d, --device-name=DEVICE   use a given scanner device (e.g. hp:/dev/scanner)
    --format=pnm|tiff|png|jpeg  file format of output file
-i, --icc-profile=PROFILE  include this ICC profile into TIFF file
-L, --list-devices         show available scanner devices
-f, --formatted-device-list=FORMAT similar to -L, but the FORMAT of the output
                           can be specified: %d (device name), %v (vendor),
                           %m (model), %t (type), %i (index number), and
                           %n (newline)
-b, --batch[=FORMAT]       working in batch mode, FORMAT is `out%d.pnm' `out%d.tif'
                           `out%d.png' or `out%d.jpg' by default depending on --format
    --batch-start=#        page number to start naming files with
    --batch-count=#        how many pages to scan in batch mode
    --batch-increment=#    increase page number in filename by #
    --batch-double         increment page number by two, same as
                           --batch-increment=2
    --batch-print          print image filenames to stdout
    --batch-prompt         ask for pressing a key before scanning a page
    --accept-md5-only      only accept authorization requests using md5
-p, --progress             print progress messages
-n, --dont-scan            only set options, don't actually scan
-T, --test                 test backend thoroughly
-A, --all-options          list all available backend options
-h, --help                 display this help message and exit
-v, --verbose              give even more status messages
-B, --buffer-size=#        change input buffer size (in kB, default 32)
-V, --version              print version information
scanimage: open of device utsushi:esci:usb:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0 failed: Operation not supported
Type ``scanimage --help -d DEVICE'' to get list of all options for DEVICE.

List of available devices:
    utsushi:esci:usb:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0

Thanks,
Matt

**Comment by paddy-hack** [comment]
See #33 for hints that might solve your problem.

The upstream sources imply that the ES-200 is supported since 3e0f2c54ed042cd7f2d8a36e557ffbd1c1a81af6.

**Comment by mburgess00** [comment]
Thanks for getting back to me so quickly. I have tried the suggestions in #33 but that didn't seem to help (output below). Issue #7 quite a while back mentioned a similar issue when the scanner wasn't plugged in to the root USB device, but this doesn't seem to be possible with the raspberry pi - all physical ports show the same in lsusb -t. 

pi@raspberrypi:~/utsushi $ sudo make -C drivers/esci install-exec
make: Entering directory '/home/pi/utsushi/drivers/esci'
Making install-exec in .   
make[1]: Entering directory '/home/pi/utsushi/drivers/esci'
 /bin/mkdir -p '/opt/libexec/utsushi'
  /bin/bash ../../libtool   --mode=install /usr/bin/install -c esci-interpreter 
'/opt/libexec/utsushi'
libtool: install: /usr/bin/install -c esci-interpreter /opt/libexec/utsushi/esci
-interpreter
 /bin/mkdir -p '/etc/udev/rules.d'
 /usr/bin/install -c -m 644 utsushi-esci.rules '/etc/udev/rules.d'
make[1]: Leaving directory '/home/pi/utsushi/drivers/esci'
Making install-exec in tests
make[1]: Entering directory '/home/pi/utsushi/drivers/esci/tests'
make[1]: Nothing to be done for 'install-exec'.
make[1]: Leaving directory '/home/pi/utsushi/drivers/esci/tests'
make: Leaving directory '/home/pi/utsushi/drivers/esci'

pi@raspberrypi:~/utsushi $ sudo scanimage -h
Usage: scanimage [OPTION]...

Start image acquisition on a scanner device and write image data to
standard output.

Parameters are separated by a blank from single-character options (e.g.
-d epson) and by a "=" from multi-character options (e.g. --device-name=epson).
-d, --device-name=DEVICE   use a given scanner device (e.g. hp:/dev/scanner)
    --format=pnm|tiff|png|jpeg  file format of output file
-i, --icc-profile=PROFILE  include this ICC profile into TIFF file
-L, --list-devices         show available scanner devices
-f, --formatted-device-list=FORMAT similar to -L, but the FORMAT of the output
                           can be specified: %d (device name), %v (vendor),
                           %m (model), %t (type), %i (index number), and
                           %n (newline)
-b, --batch[=FORMAT]       working in batch mode, FORMAT is `out%d.pnm' `out%d.tif'
                           `out%d.png' or `out%d.jpg' by default depending on --format
    --batch-start=#        page number to start naming files with
    --batch-count=#        how many pages to scan in batch mode
    --batch-increment=#    increase page number in filename by #
    --batch-double         increment page number by two, same as
                           --batch-increment=2
    --batch-print          print image filenames to stdout
    --batch-prompt         ask for pressing a key before scanning a page
    --accept-md5-only      only accept authorization requests using md5
-p, --progress             print progress messages
-n, --dont-scan            only set options, don't actually scan
-T, --test                 test backend thoroughly
-A, --all-options          list all available backend options
-h, --help                 display this help message and exit
-v, --verbose              give even more status messages
-B, --buffer-size=#        change input buffer size (in kB, default 32)
-V, --version              print version information
scanimage: open of device utsushi:esci:usb:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0 failed: Operation not supported
Type ``scanimage --help -d DEVICE'' to get list of all options for DEVICE.

List of available devices: 
    utsushi:esci:usb:/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1.2/1-1.1.2:1.0

pi@raspberrypi:~/utsushi $ lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 3, If 0, Class=Hub, Driver=hub/3p, 480M
            |__ Port 1: Dev 5, If 0, Class=Vendor Specific Class, Driver=lan78xx, 480M
            |__ Port 2: Dev 14, If 0, Class=Vendor Specific Class, Driver=, 480M

**Comment by mburgess00** [comment]
I'm not sure what might have happened here, but building the utsushi as distributed by Epson worked - closing

**Comment by paddy-hack** [comment]
Thanks for the feedback.  
I've just looked at the differences between Epson's imagescan and utsushi.  One thing that stood out was a minor difference in the `install-deps` script.  The version in utsushi does not install recommended packages so I was wondering if a missing dependency might have caused this.

Did you use that script?  Did it install extra packages for Epson's imagescan?
