### ISSUE TITLE
can't compile with included boost (C++11 mode @ openSUSE thumbleweed)

### ISSUE THREAD

**Issue by quatrox** [utsushi/utsushi#52]
steps to reproduce:
$ git clone https://github.com/utsushi/utsushi.git
$ cd utsushi
$ tools/include-boost-src

now boost is placed where configure won't find it, so we better move it
$ cd upstream
$ mv boost boost.old
$ mv downloads/boost_1_49_0 boost
$ cd ..

$ ./bootstrap
$ ./configure --enable-sane-config --enable-udev-config --with-jpeg --with-magick --with-sane --with-included-boost --with-tiff --with-gtkmm --with-magick-pp

$ make
make fails, so lets fix the first issue:
In utsushi/functional.hpp, we need to ensure we use C++11 implementation when compiling with C++11, so we need to change from
   #if __cplusplus >= 201103L && !WITH_INCLUDED_BOOST
to
   #if __cplusplus >= 201103L

The next problem is that boost/thread/xtime.hpp declares boost::TIME_UTC, but TIME_UTC is a MACRO which is included from a system lib, so I chose to rename boost::TIME_UTC to boost::E_TIME_UTC (in the whole project).

Then, on the current version, it is even more compilation errors, so it is hard to get it to build.

**Comment by quatrox** [comment]
I also noticed that make tries to run ./bootstrap.sh if it can't find boost, but the bootstrap file is called "bootstrap" and not "bootstrap.sh".

**Comment by paddy-hack** [comment]
The included Boost is old at 1.49.0.  At a time, it was newer than what was available from distributions so including it made sense.  Now it no longer really does.  Please install your distributions Boost development library packages.  Those will be used in preference to anything that is included.  
I guess I should rip out this now outdated "included Boost" stuff (#53).  Should simplify things a good deal too.

The `TIME_UTC` issue is with Boost, not utsushi :smile:  
The `bootstrap.sh` is the one from Boost, not utsushi :smile:
