### ISSUE TITLE
Missing INSTALL

### ISSUE THREAD

**Issue by jlpoolen** [utsushi/utsushi#6]
The instructions in README state:

```
 BUILDING/INSTALLING FROM SOURCE
 ===============================
   Generic installation notes can be found in the 'INSTALL' file.
```

I did the following:

```
 git clone https://github.com/utsushi/utsushi
 cd utsushi
 [There is no INSTALL file.]
 find . -name "INSTALL"
 [Nothing returned]
 [Moreover, there is no file "configure", so my attempt to invoke "./configure" fails]
```

Is the INSTALL file missing?

**Comment by jlpoolen** [comment]
```
jlpoole@themis /usr/local/src/utsushi $ pwd
/usr/local/src/utsushi
jlpoole@themis /usr/local/src/utsushi $ ls -la
total 204
drwxr-xr-x 18 jlpoole jlpoole  4096 Sep 17 12:59 .
drwxrwxrwx 57 root    root     4096 Sep 17 12:59 ..
-rw-r--r--  1 jlpoole jlpoole  1501 Sep 17 12:59 AUTHORS
-rwxr-xr-x  1 jlpoole jlpoole  8727 Sep 17 12:59 bootstrap
-rw-r--r--  1 jlpoole jlpoole    69 Sep 17 12:59 ChangeLog
-rw-r--r--  1 jlpoole jlpoole  1433 Sep 17 12:59 config-bot.h
-rwxr-xr-x  1 jlpoole jlpoole 22863 Sep 17 12:59 configure.ac
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 connexions
-rw-r--r--  1 jlpoole jlpoole 35147 Sep 17 12:59 COPYING
drwxr-xr-x  3 jlpoole jlpoole  4096 Sep 17 12:59 doc
drwxr-xr-x  3 jlpoole jlpoole  4096 Sep 17 12:59 drivers
drwxr-xr-x  4 jlpoole jlpoole  4096 Sep 17 12:59 filters
drwxr-xr-x  7 jlpoole jlpoole  4096 Sep 17 12:59 .git
-rw-r--r--  1 jlpoole jlpoole  2072 Sep 17 12:59 .gitignore
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 gtkmm
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 include
-rwxr-xr-x  1 jlpoole jlpoole  6624 Sep 17 12:59 install-deps
drwxr-xr-x  3 jlpoole jlpoole  4096 Sep 17 12:59 lib
-rw-r--r--  1 jlpoole jlpoole 10109 Sep 17 12:59 Makefile.am
-rw-r--r--  1 jlpoole jlpoole  9072 Sep 17 12:59 NEWS
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 outputs
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 po
-rw-r--r--  1 jlpoole jlpoole  7349 Sep 17 12:59 README
drwxr-xr-x  3 jlpoole jlpoole  4096 Sep 17 12:59 sane
drwxr-xr-x  3 jlpoole jlpoole  4096 Sep 17 12:59 src
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 tests
drwxr-xr-x  2 jlpoole jlpoole  4096 Sep 17 12:59 tools
-rw-r--r--  1 jlpoole jlpoole  1081 Sep 17 12:59 .travis.yml
drwxr-xr-x  3 jlpoole jlpoole  4096 Sep 17 12:59 upstream
drwxr-xr-x  4 jlpoole jlpoole  4096 Sep 17 12:59 utsushi
jlpoole@themis /usr/local/src/utsus find . -name "INSTALL"
jlpoole@themis /usr/local/src/utsushi $
```

**Comment by paddy-hack** [comment]
Thanks for pointing this out.  The git repository only includes what I call "original" sources.  Things like the `INSTALL` file and `configure` script are generated by tools.  I don't see the point of putting those under version control.

To create the generated files, you need to run the `./bootstrap` script.  Please note that that script assumes you have the `autoconf`, `automake`, `autopoint` (part of `gettext`), `libtoolize`, `patch` and `gnulib-tool`  available.

I guess I should document this prominently and maybe make `bootstrap` advertise its requirements.

**Comment by jlpoolen** [comment]
My experience (mostly Gentoo where everything is built right on our machine) is that having the INSTALL and configure scripts are a good thing to have to make a package completely portable.  My usual procedure for any new Linux build is to read the INSTALL, run ./configure --help to see what options I have, then run ./configure with options I have selected then make, make test, and make install.  

If you are not going to have the customary files, then, yes, you do need to provide documentation.

I recommend you include the INSTALL and configure script, at least having those will make it easier to include your product in Gentoo as someone would simply write a wrapper script for it.

**Comment by paddy-hack** [comment]
If you prefer that, you may be interested in the [imagescan Source Code Archives](http://utsushi.github.io/imagescan/).  Of course, you miss out on all the fixes and "extras" provided by the Utsushi community Code Base (none as of writing because `imagescan-3.12.0` merged all of them :wink:).

**Comment by pniederlag** [comment]
@paddy-hack +1 for adding a hint on bootstrap.sh for usage of this repo

**Comment by Qwertie-** [comment]
The readme file should say to run ./bootstrap before ./configure
