### ISSUE TITLE
Epson DS-560 network scanning

### ISSUE THREAD

**Issue by sirjaren** [utsushi/utsushi#8]
Hello @paddy-hack,

I've been playing with an _Epson DS-560_, and I've been unable to get the scanner to work over a network.  I've not tried using a USB cord as I am not intending to use a physical connection.
## The setup
- _Epson DS-560_ (connected to router with static IP address)
- Computer (running `Gentoo`) attached to router (static IP)
## Intention
- To use the computer to scan over the network
## Verification of network connectivity

I've verified I can connect from my computer to the scanner on port 1865:

<pre>
<b>$ ping -c2 scanner</b>
PING epson-scanner (192.168.1.231) 56(84) bytes of data.
64 bytes from epson-scanner (192.168.1.231): icmp_seq=1 ttl=64 time=90.3 ms
64 bytes from epson-scanner (192.168.1.231): icmp_seq=2 ttl=64 time=112 ms

--- epson-scanner ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 90.335/101.593/112.852/11.263 ms

<b>$ telnet scanner 1865 <<< 'quit'</b>
Trying 192.168.1.231...
Connected to scanner.
Escape character is '^]'.
Connection closed by foreign host.

<b>$ nmap scanner -p 0-2000</b>
Starting Nmap 6.25 ( http://nmap.org ) at 2015-10-10 10:29 CDT
Nmap scan report for scanner (192.168.1.231)
Host is up (0.021s latency).
rDNS record for 192.168.1.231: epson-scanner
Not shown: 1999 closed ports
PORT     STATE SERVICE
80/tcp   open  http
1865/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.87 seconds
</pre>

##### epkowa
-  Tried with `iscan-network-nt` package (to have `/usr/lib/iscan-data/network` try and connect to the scanner)
- I've configured `/etc/sane.d/epkowa.conf` to use my static IP (eg. `net scanner 1865`)
- I've configured `/etc/sane.d/dll.conf` to use only these values:
  - `net` (which may be unneeded since it appears `epkowa` uses `iscan-network-nt` to call `/usr/lib/iscan-data/network` to do the networking?)
  - `epkowa`
- `sane-find-scanner` never seems to do anything for me
- `scanimage -L` is what I've been using for testing
  - Only _once_ have I been able to get `scanimage` to return my scanner (and IP)
  - A subsequent query was fruitless
- Sometimes I check with `gimp` and `iscan` as just another check (which has not helped)
##### utsushi (compiled from source)

<pre>
<b>$ utsushi version</b>
utsushi (Utsushi) 0.13.0
Copyright (C) 2012-2015  SEIKO EPSON CORPORATION
License: GPL-3.0+

<b>Configuration options:</b>
--enable-sane-config
--enable-udev-config
--with-gtkmm
--with-jpeg
--with-magick
--with-sane
--with-tiff
</pre>
- I've removed the `iscan` and `iscan-data` packages
- Added this to `/etc/sane.d/dll.conf` to use only these values:
  - `net`
  - `utsushi`
- So far, I've been unable to find enough information about `utsushi` to do much else other than try using `scanimage -L` to try and test connectivity
##### epsonds

I've been unable to test this driver as I've not tried compiling `sane-backends` from `git` to enable the necessary backend
## Conclusion

I've found that I've come close to being able to scan using `epkowa` and `iscan-network-nt` but I don't believe this is directly supported.

Any thoughts?  I have lots of debugging information and logs, but I wanted to see if I'm missing something.

Thanks!

**Comment by paddy-hack** [comment]
The `epkowa` backend does _not_ support the DS-560.  The DS-560 uses a very different device protocol from the protocol supported by the `epkowa` (and `epson2` and `epson`) backend(s).  Adding the `iscan-network-nt` plugin doesn't change that one single bit.

The `epsonds` backend supports the device protocol used by the DS-560 but I don't know if it also caters to the additional protocol layer needed to make things work over a network connection.

Finally, `utsushi` only supports the DS-560 over a USB connection.  There is a non-free plugin available from the [EPSON Download Center](http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX) that can be used with `utsushi` to make things work over a network connection.

**Comment by sirjaren** [comment]
Thanks for the help paddy-hack!

I managed to get the `utsushi` backend to work with the _DS-560_ over a wireless connection.  I'll explain what I did below in the event it may help someone else.

I'll start off by saying the reason I was having trouble was the fact I was downloading the _source_ driver package from the [EPSON Download Center](http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX), not realizing the compiled, distribution-specific, packages included non-free plugins for use.  Is this documented anywhere?

## Installation & configuration

This happens in two parts.  The first is installing the `utsushi` (`imagescan`) package.  Next, is installing the `networkscan` plugin (which is very similar to the `iscan-network-nt` plugin to be used with the `epkowa` backend).  Finally, SANE is configured to be `utsushi` aware.

**NOTE:** The below directions are for manually installing the the necessary packages to get the functionality required.  It's preferable to install the pre-built packages for your system of choice (available on the [EPSON Download Center](http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX) website).

You can also use my _ebuilds_ if on a `Gentoo` system.  The _ebuilds_ or distribution packages will provide the the `docs` and licenses that are provided by Epson.

Again, below is just a manual way of installing the files and to give a brief overview of the structure on how to configure the SANE backend to be aware of your scanner.

#### Driver

##### `utsushi`

I compiled the `utsushi` backend from source, opting to have this 'core' package perform the configuration installs (where applicable).  I made a `Gentoo` _ebuild_ that will perform the install, located here:

[epson-ds](https://github.com/sirjaren/gentoo-overlay/tree/master/media-gfx/epson-ds)

Outside of using an _ebuild_, one can configure and install it locally (`/usr/local` or wherever).  A good set of defaults to use when configuring the source package is (defaulting to `/usr/local`):

<pre>
<b>Configuration options:</b>
--enable-sane-config
--enable-udev-config
--with-gtkmm
--with-jpeg
--with-magick
--with-sane
--with-tiff
</pre>

Once configured, a `make` and `make install` will perform the package installation.  This package (with the above configuration options) provides a SANE configuration file as well as `udev` rules.  These are installed in the default locations, which can be changed with more configuration options.

There is no need to add the `utsushi` entry to `/etc/sane.d/dll.conf` as this package will provide a file called `utsushi` located in `/etc/sane.d/dll.d/` with the entry, `utsushi`, to be picked up by the SANE backend.

#### Plugin

##### `networkscan`

Once the `utsushi` backend has been installed, this `networkscan` plugin is needed to provide the networking support.

For `Gentoo` users, I've create an _ebuild_ which can be used to install the `networkscan` plugin.  This is located here:

[epson-ds-plugins](https://github.com/sirjaren/gentoo-overlay/tree/master/media-gfx/epson-ds-plugins)

For others, the trick is to download a pre-built package from the [EPSON Download Center](http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX).  In my case (and the case of the _ebuild_ I created), I used these packages (you can, presumably, use any other package that has the word _bundle_ in it, considering your architecture):

<pre>
<b>[32bit]</b> imagescan-bundle-centos-6-1.0.3.x86.rpm.tar.gz
<b>[64bit]</b> imagescan-bundle-centos-6-1.0.3.x64.rpm.tar.gz
</pre>

Choose the right package for the architecture you're installing to, and extract the gzipped tar file.

Once extracted, there are two `rpm` packages (one in the `core` directory and one on the `plugins` directory).  These need to be extracted as well.

In the `core` directory (where one of the `rpm`'s was extracted), there is a file called `imagescan.conf` located in `core/<extracted_rpm>/etc/imagescan/`.  This file should be installed as `/etc/utsushi/utsushi.conf`.  This file configures the scanner to use the `networkscan` plugin.  In my config, I have the following:

<pre>
<b>/etc/utsushi/utsushi.conf:</b>
[devices]
office.udi    = networkscan:esci://192.168.1.231:1865
office.vendor = Epson
office.model  = DS-560
office.name   = [office] Epson DS-560
</pre>

In the `plugins` directory (where one of the `rpm`'s was extracted), there is the non-free binary called `networkscan` located in `plugins/usr/libexec/utsushi/`.  This binary should be installed as `/usr/libexec/utsushi/networkscan`.  Keep in mind, this could be `/usr/local/` depending on how you've installed the `utsushi` backend.

## Finishing up

Once done, assuming you have no other networking issues, you should be able to scan successfully.  You can test the various interfaces:

##### SANE backend

<pre>
<b>$ scanimage -L</b>
device `utsushi:networkscan:esci://192.168.1.231:1865' is a Epson DS-560
</pre>

##### Directly with `utsushi`

<pre>
<b>$ utsushi list</b>
networkscan:esci://192.168.1.231:1865
<b>$ utsushi scan --no-interface > scan.test</b>
<b>$ file scan.test</b>
scan.test: Netpbm PPM "rawbits" image data, size = 2550 x 4200
</pre>

##### Or, if compiled with the GTK (`gtkmm`) interface

<pre>
<b>$ utsushi scan</b>
</pre>

I hope this helps anyone else having issues or wondering how to make this work.  Maybe this could be used as a part of a wiki or something?

Anyways, thanks again for your help paddy-hack!

**Comment by paddy-hack** [comment]
You're welcome.  With respect to documentation for the [EPSON Download Center](http://download.ebz.epson.net/dsc/search/01/search/?OSC=LX) packages, ask EPSON.  Their [imagescan Source Code Archives](http://utsushi.github.io/imagescan/) are tracked by the Utsushi project but that's it.

Non-free code?  :angry:
No, thank you!

Your write up is correct and to the point.  It could be the start of a wiki or user documentation material.  However, if there are binary packages that already do all that stuff, why bother?

Out of curiosity and because of #7, have you tried scanning via USB?

**Comment by sirjaren** [comment]
I agree regarding non-free code -- blegh!

Unfortunately, if I do have a need for the wireless connectivity, and considering the cost of the DS-560, the non-free plugin is necessary, if not ideal. :disappointed:

Regarding the binary packages, I suppose it's not necessary.  For me, it was nice to see all the code/files laid out so I knew what went where and why.

The whole `imagescan` -> `utsushi` is still a bit confusing for me, not to mention the **Avasys** - **Epson** (or is it **Epson** -> **Avasys** now that Epson acquired the majority stake in **Avasys Corporation**?  See Epson's [press release](http://global.epson.com/newsroom/2015/news_20150303.html)). Confusing.

I took a look at #7 and I may have found something that may help.

##### Diagnostics for direct USB connection

<pre>
<i># Force using the USB connection by disabling the network configuration</i>
<b>$ mv /etc/utsushi /etc/utsushi.bak</b>
<b>$ scanimage -L</b>
device `utsushi:usb:esci:/sys/devices/pci0000:00/0000:00:1d.7/usb1/1-1/1-1:1.0' is a EPSON Epson_DS-560
<b>$ sane-find-scanner -q</b>
found USB scanner (vendor=0x04b8 [EPSON], product=0x0150 [Epson DS-560]) at libusb:001:013
<b>$ scanimage > test.usb.pnm</b>
<b>$ file test.usb.pnm</b>
test.usb.pnm: Netpbm PPM "rawbits" image data, size = 2549 x 4199
</pre>

The above shows that I can, in fact use the USB connection.

I was able to reproduce @jlpoolen's issue by plugging the USB connection into a USB hub.  In my case, I plugged the scanner into my USB powered keyboard (which provides additional USB inputs for other peripheral devices).

##### Diagnostics for USB hub connection

<pre>
<i># Force using the USB connection by disabling the network configuration</i>
<b>$ mv /etc/utsushi /etc/utsushi.bak</b>
<i># Notice the different USB address</i>
<b>$ scanimage -L</b>
device `utsushi:usb:esci:/sys/devices/pci0000:00/0000:00:1d.7/usb1<b>/1-3/1-3.4/1-3.4:1.0</b>' is a EPSON Epson_DS-560
<i># Note the different address</i>
<b>$ sane-find-scanner -q</b>
found USB scanner (vendor=0x04b8 [EPSON], product=0x0150 [Epson DS-560]) at <b>libusb:001:014</b>
<b>$ scanimage > test.usb.pnm</b>
scanimage: open of device utsushi:usb:esci:/sys/devices/pci0000:00/0000:00:1d.7/usb1/1-3/1-3.4/1-3.4:1.0 failed: Operation not supported
<b>$ SANE_DEBUG_DLL=128 scanimage > test.usb.pnm</b>
[sanei_debug] Setting debug level of dll to 128.
[dll] sane_init: SANE dll backend version 1.0.13 from sane-backends 1.0.25git
[dll] sane_init/read_dlld: attempting to open directory `./dll.d'
[dll] sane_init/read_dlld: attempting to open directory `/etc/sane.d/dll.d'
[dll] sane_init/read_dlld: using config directory `/etc/sane.d/dll.d'
[dll] sane_init/read_dlld: considering /etc/sane.d/dll.d/utsushi
[dll] sane_init/read_config: reading dll.d/utsushi
[dll] add_backend: adding backend `utsushi'
[dll] sane_init/read_dlld: done.
[dll] sane_init/read_config: reading dll.conf
[dll] sane_get_devices
[dll] load: searching backend `utsushi' in `/usr/lib/sane'
[dll] load: trying to load `/usr/lib/sane/libsane-utsushi.so.1'
[dll] load: dlopen()ing `/usr/lib/sane/libsane-utsushi.so.1'
[dll] init: initializing backend `utsushi'
[dll] init: backend `utsushi' is version 1.1.0
[dll] sane_get_devices: found 1 devices
[dll] sane_open: trying to open `utsushi:usb:esci:/sys/devices/pci0000:00/0000:00:1d.7/usb1/1-3/1-3.4/1-3.4:1.0'
scanimage: open of device utsushi:usb:esci:/sys/devices/pci0000:00/0000:00:1d.7/usb1/1-3/1-3.4/1-3.4:1.0 failed: Operation not supported
[dll] sane_exit: exiting
[dll] sane_exit: calling backend `utsushi's exit function
[dll] sane_exit: finished
</pre>

Hopefully, this helps track down the issue.  I can confirm that I am able to scan via USB for the _Epson DS-560_ if plugged directly into a USB port provided by the computer.

**Comment by jlpoolen** [comment]
Note: I have the network module for the DS-70000, but have not installed it.  Currently, the DS-70000 is not working with utsushi, see Issue #7.  I don't want to introduce another variable into the problem by using the network mode.

**Comment by sirjaren** [comment]
Hi jlpoolen,

paddy-hack was asking if I tested the USB connection (in addition to the `networkscan` plugin).

I found I was able to get the USB connection to work if I plugged the scanner directly into my computer, but not via a USB hub (which didn't work).

I'm also on a `Gentoo` system.

**Comment by paddy-hack** [comment]
Thanks! :heart_eyes:  I should have asked @jlpoolen to do an `lsusb -t` but I'll take that to #7.

Your original issue is, I think, resolved.  You got network scanning for your DS-560 working, so I'll close this issue.

**Comment by jlpoolen** [comment]
sirjaren - would you please provide the output of `lsusb -t` when your scanner is plugged into your computer directly (not through a hub) and is working.  It seems my Dell Insprion N7010 only has USB ports on it that are served by an internal hub controller.  Your machine seems to have a "Tier 1" (term from paddy-hack in my Issue #7) USB port and I'd like to see how your class of USB support is represented on an `lsusb -t` output.

Edit: I'm wondering if USB Port configuration is purely hardware driven, or is it configurable through the kernel and/or drivers.

**Comment by jlpoolen** [comment]
This may be helpful to readers: https://wiki.gentoo.org/wiki/USB/Guide at Configure Options For the Kernel.  I'm going to review my kernel and see if I may have settings that could alter the "Class" of my USB ports.

**Comment by sirjaren** [comment]
Sure thing jlpoolen.  I'll go ahead and provide the information on #7.

And I'll take a look at your _ebuild_ woes today. Thanks!
