### ISSUE TITLE
scanimage -T fails: Assertion `px != 0' failed.

### ISSUE THREAD

**Issue by jlpoolen** [utsushi/utsushi#9]
I installed my network interface on my DS-70000 given the results of the project https://github.com/sirjaren/gentoo-overlay, specifically the epson-ds and epson-ds-plugins packages for Gentoo.  Herein, see Issue #7 where I have been unsuccessful in connecting the DS-70000 to my laptop directly.   

After installing the aforesaid Gentoo packages and using the network interface, I appear to be shaking hands with the scanner.  So, first thing I did was try some sample scans and they failed inevitably with:

```
themis local # scanimage >/tmp/test.tiff
scanimage: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = utsushi::filter; typename boost::detail::sp_member_access<T>::type = utsushi::filter*]: Assertion `px != 0' failed.
Aborted
themis local #
```

So then I backed-off and started with what should be a basic diagnostic, "scanimage -T".  Here are the results:

```
themis local # scanimage -L
device `utsushi:networkscan:esci://192.168.1.50:1865' is a Epson DS-70000 
themis local # scanimage -T
scanimage: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = utsushi::filter; typename boost::detail::sp_member_access<T>::type = utsushi::filter*]: Assertion `px != 0' failed.
Aborted
themis local # 
```

**Comment by jlpoolen** [comment]
I should note that the utsushi files from my pristine build were altered by the Gentoo packages:
- Detected file collision(s):
  - 
  -  /usr/lib64/sane/libsane-utsushi.so.1.0.24
  -  /usr/lib64/sane/libsane-utsushi.la
  -  /usr/lib64/sane/libsane-utsushi.a
  -  /usr/lib64/sane/libsane-utsushi.so.1
  -  /usr/lib64/sane/libsane-utsushi.so
  - 
  - Searching all installed packages for file collisions...
  - 
  - Press Ctrl-C to Stop
  - 
  - None of the installed packages claim the file(s).
  - 
  - Package 'media-gfx/epson-ds-3.13.0' merged despite file collisions. If
  - necessary, refer to your elog messages for the whole content of the
  - above message.

I realize that having the epson-ds project overwrite this project's libraries may make problem resolution untenable.

**Comment by sirjaren** [comment]
Well, this looks like a `boost` issue.

Btw, the overwriting of these files is going to happen if you've installed software 'locally' in the system-wide location.  It's recommended, when compiling and installing manually, to install to `/usr/local/` or some other place that won't interfere with your distribution's package manager.

In this instance, since `portage` coudn't find any installed package owning the files you created by yourself (which is to be expected), `portage` will happily install over them.

I would recommend uninstalling via `emerge -aC epson-ds` and then uninstall via your local installation (`make uninstall`).

That will clean your environment out.  Also, if you've moved files around manually,  you may want to do manual cleanup.

I don't have `boost` support in the `epson-ds` _ebuild_, but I'll play around with it to see if I can't reproduce this and/or fix it.

**Comment by jlpoolen** [comment]
I removed my manual install of epson-ds and I utilized `make uninstall` for the utsushi [utsushi_jlp] project followed by `make install` to regenerate the executables/libraries as they were meant to be by utsushi.  I then installed epson-ds using layman with the revised install instructions for that project.  I'm back to the place where I was when this issue was opened:

```
themis utsushi_jlp # scanimage >/tmp/test.tiff
scanimage: /usr/include/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = utsushi::filter; typename boost::detail::sp_member_access<T>::type = utsushi::filter*]: Assertion `px != 0' failed.
Aborted
themis utsushi_jlp #
```

But this time, I'm in sync with the repository so I can easily pull changes.

**Comment by sirjaren** [comment]
I've played with the configuration and manually mucked with files and it appears that you _cannot_ have the `utsushi` driver installed _without_ `boost` support.

I tried this for the `./configure` stage:

<pre>
--with-boost=no
--without-boost
--without-included-boost
--without-boost-system
--without-boost-filesystem
--without-boost-iostreams
--without-boost-program-options
--without-boost-regex
--without-boost-thread
--without-boost-unit-test-framework
</pre>

After which, I removed references to the `boost` libraries in the generated `Makefile` for `LIBUTSUSHI_LIBS`.

I'm unable to compile without `boost` as a dependency.

The only thing I believe I can do, is add support for switching between the system `boost` libraries (provided via `gentoo`) or the included `boost` libraries (provided via `utsushi`).

I'd recommend trying to use the package-included `boost` libraries and see how that fares in comparison with the system `boost` libraries.

If that fails, try again but use your system `boost` libraries.

I can try and add support for this in `epson-ds-3.13.0.ebuild`.

**Comment by paddy-hack** [comment]
Eh, no, `boost` is not an option.  Your system's `boost` libraries are preferred.  The (partial and old) copy included in the [imagescan archive](https://github.com/utsushi/imagescan/tree/archive) is only for the benefit of users stuck with ancient distributions.

To help troubleshoot the issue, please modify `lib/log.cpp` to have:

```
log::priority log::threshold = log::DEBUG;
log::category log::matching  = log::ALL;
```

recompile, install and provide the log output for the above error (a shared pointer to a non-existent object).

**Comment by jlpoolen** [comment]
I went to `/usr/local/src/utsushi_jlp/lib/log.cpp` and found that I already have the logging modified pursuant to a prior request:

```
namespace utsushi {

  //log::priority log::threshold = log::FATAL;
  log::priority log::threshold = log::DEBUG;
  //log::category log::matching  = log::NOTHING;
  log::category log::matching  = log::ALL;
```

I returned to      `/usr/local/src/utsushi_jlp/` and typed `make` and got nothing:

```
themis utsushi_jlp # make
make  all-recursive
make[1]: Entering directory '/usr/local/src/utsushi_jlp'
Making all in .
make[2]: Entering directory '/usr/local/src/utsushi_jlp'
make[2]: Leaving directory '/usr/local/src/utsushi_jlp'
Making all in lib
make[2]: Entering directory '/usr/local/src/utsushi_jlp/lib'
Making all in .
...
```

So I made an edit doubling up a line, tried make, got an error message, then removed my offending line and make then make install.  The session log is at: http://pastebin.com/tDDZnsLp
Here's my subsequent attempt:

```
themis utsushi_jlp #  scanimage >/tmp/test.tiff
2015-Oct-19 03:53:11.344795[7fc370282700]: sane_utsushi_init: SANE 'utsushi' backend (1.1.0), a part of Utsushi 0.12.0
2015-Oct-19 03:53:11.345013[7fc370282700]: sane_utsushi_get_devices: invalidated SANE_Device pointers
2015-Oct-19 03:53:11.425535[7fc370282700]: sane_utsushi_get_devices: added networkscan:esci://192.168.1.50:1865 to device pool
2015-Oct-19 03:53:13.074815[7fc370282700]: sane_utsushi_open: creating SANE_Handle for networkscan:esci://192.168.1.50:1865
2015-Oct-19 03:53:13.075121[7fc370282700]: sane_utsushi_open: unhandled exception
/usr/local/libexec/utsushi/networkscan: not executable
2015-Oct-19 03:53:13.075166[7fc370282700]: sane_utsushi_open: Operation not supported
scanimage: open of device utsushi:networkscan:esci://192.168.1.50:1865 failed: Operation not supported
2015-Oct-19 03:53:13.075272[7fc370282700]: sane_utsushi_exit: closing open handles
themis utsushi_jlp # ping  192.168.1.50
PING 192.168.1.50 (192.168.1.50) 56(84) bytes of data.
64 bytes from 192.168.1.50: icmp_seq=1 ttl=64 time=0.682 ms
64 bytes from 192.168.1.50: icmp_seq=2 ttl=64 time=0.349 ms
^C
--- 192.168.1.50 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.349/0.515/0.682/0.168 ms
themis utsushi_jlp #
```

**Comment by jlpoolen** [comment]
# HO! "It lives."

```
themis utsushi_jlp # ls /usr/local/libexec/utsushi/
doc-locate    utsushi-list  utsushi-scan      utsushi-version
utsushi-help  utsushi-main  utsushi-scan-cli
themis utsushi_jlp # ls -la /usr/local/libexec/utsushi/
total 6388
drwxr-xr-x 2 root root    4096 Oct 19 03:47 .
drwxr-xr-x 3 root root    4096 Sep 19 04:10 ..
-rwxr-xr-x 1 root root  145843 Oct 19 03:47 doc-locate
-rwxr-xr-x 1 root root  189944 Oct 19 03:47 utsushi-help
-rwxr-xr-x 1 root root  283328 Oct 19 03:47 utsushi-list
-rwxr-xr-x 1 root root  636328 Oct 19 03:47 utsushi-main
-rwxr-xr-x 1 root root  797504 Oct 19 03:47 utsushi-scan
-rwxr-xr-x 1 root root 4274976 Oct 19 03:47 utsushi-scan-cli
-rwxr-xr-x 1 root root  189952 Oct 19 03:47 utsushi-version
themis utsushi_jlp # updatedb
themis utsushi_jlp # locate networkscan
/usr/libexec/utsushi/networkscan
themis utsushi_jlp # ln -s /usr/libexec/utsushi/networkscan /usr/local/libexec/utsushi/networkscan
themis utsushi_jlp #  scanimage >/tmp/test.tiff
2015-Oct-19 03:57:43.441860[7f6b79923700]: sane_utsushi_init: SANE 'utsushi' backend (1.1.0), a part of Utsushi 0.12.0
2015-Oct-19 03:57:43.442142[7f6b79923700]: sane_utsushi_get_devices: invalidated SANE_Device pointers
2015-Oct-19 03:57:43.465838[7f6b79923700]: sane_utsushi_get_devices: added networkscan:esci://192.168.1.50:1865 to device pool
2015-Oct-19 03:57:44.644772[7f6b79923700]: sane_utsushi_open: creating SANE_Handle for networkscan:esci://192.168.1.50:1865
2015-Oct-19 03:57:44.645637[7f6b79923700]: /usr/local/libexec/utsushi/networkscan[6048]: starting
2015-Oct-19 03:57:44.650466[7f6b79923700]: opened ipc::connexion to: //192.168.1.50:1865
2015-Oct-19 03:57:44.650583[7f6b79923700]: looking for preloaded 'esci' driver
2015-Oct-19 03:57:44.650637[7f6b79923700]: looking for 'esci' driver in '/usr/local/lib/utsushi'
2015-Oct-19 03:57:44.652360[7f6b79923700]: using '/usr/local/lib/utsushi/libdrv-esci'
2015-Oct-19 03:57:45.025453[7f6b79923700]: detected a 'DS-70000'
2015-Oct-19 03:57:45.025969[7f6b79923700]: getting basic device information
2015-Oct-19 03:57:45.545546[7f6b79923700]: trying to get device information from file
2015-Oct-19 03:57:45.545873[7f6b79923700]: INFO: 356 byte payload
2015-Oct-19 03:57:45.546282[7f6b79923700]: CAPA: 312 byte payload
2015-Oct-19 03:57:45.546594[7f6b79923700]: CAPB: 0 byte payload
2015-Oct-19 03:57:45.546627[7f6b79923700]: RESA: 1224 byte payload
2015-Oct-19 03:57:45.547111[7f6b79923700]: RESB: 0 byte payload
2015-Oct-19 03:57:45.547167[7f6b79923700]: using device information from file
2015-Oct-19 03:57:45.547202[7f6b79923700]: using device capabilities from file
2015-Oct-19 03:57:45.550133[7f6b79923700]: waiting for cancellation to complete
2015-Oct-19 03:57:45.550412[7f6b6cefe700]: using UM08 profile
2015-Oct-19 03:57:46.095325[7f6b6cefe700]: starting acquisition of image(s)
2015-Oct-19 03:57:48.050549[7f6b6cefe700]: starting acquisition of face side image
2015-Oct-19 03:57:48.051824[7f6b6c6fd700]: shell-pipe: buffer size now 65536 octets
2015-Oct-19 03:57:48.051906[7f6b6c6fd700]: gm convert started (pid: 6052)
2015-Oct-19 03:57:48.051932[7f6b6c6fd700]: invocation: gm convert  -size 1169x1699 -depth 8 -density 100x100 -units PixelsPerInch - -density 100x100 -depth 8 rgb:-
2015-Oct-19 03:57:48.052020[7f6b79923700]: sane_utsushi_get_parameters: RGB frame
2015-Oct-19 03:57:48.052084[7f6b79923700]: sane_utsushi_get_parameters: 1699 lines
2015-Oct-19 03:57:48.052125[7f6b79923700]: sane_utsushi_get_parameters: 1169 pixels/line
2015-Oct-19 03:57:48.052167[7f6b79923700]: sane_utsushi_get_parameters: 3507 bytes/line (0 padding)
2015-Oct-19 03:57:48.052210[7f6b79923700]: sane_utsushi_get_parameters: 8 bits/sample
2015-Oct-19 03:57:48.052248[7f6b79923700]: sane_utsushi_get_parameters: last frame: yes
2015-Oct-19 03:57:50.785492[7f6b6cefe700]: finished acquisition of face side image
2015-Oct-19 03:57:50.785761[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:50.785870[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:50.785928[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:50.785953[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:50.786028[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:50.786204[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:50.786277[7f6b6c6fd700]: buffer::sync: cannot write to output
2015-Oct-19 03:57:51.010917[7f6b79923700]: sane_utsushi_read: 8192 bytes (of 32768 requested)

...


2015-Oct-19 03:57:51.050905[7f6b79923700]: sane_utsushi_read: 2809 bytes (of 32768 requested)
2015-Oct-19 03:57:51.050941[7f6b79923700]: sane_utsushi_read: 0 bytes (of 32768 requested)
2015-Oct-19 03:57:51.050972[7f6b79923700]: sane_utsushi_read: End of file reached
2015-Oct-19 03:57:51.051877[7f6b6c6fd700]: terminating /usr/local/libexec/utsushi/networkscan (port 59087)
2015-Oct-19 03:57:51.051898[7f6b79923700]: sane_utsushi_exit: closing open handles
2015-Oct-19 03:57:51.052327[7f6b6c6fd700]: /usr/local/libexec/utsushi/networkscan[6048]: exited with status 0
themis utsushi_jlp #
```

**Comment by paddy-hack** [comment]
It appears you found your missing link :wink: 

Plugin searching and logging support could use some improvement but that is food for other issues.
